# Generated by Django 5.2.14 on 2026-05-18 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'departments',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.TextField(db_column='employee_code', unique=True)),
                ('first_name', models.TextField(db_column='first_name')),
                ('last_name', models.TextField(db_column='last_name')),
                ('email', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('role', models.TextField(blank=True, null=True)),
                ('salary_type', models.TextField(db_column='salary_type', default='monthly')),
                ('salary_amount', models.DecimalField(blank=True, db_column='salary_amount', decimal_places=2, max_digits=10, null=True)),
                ('status', models.TextField(default='active')),
                ('bank_name', models.TextField(blank=True, db_column='bank_name', null=True)),
                ('bank_account', models.TextField(blank=True, db_column='bank_account', null=True)),
                ('bank_ifsc', models.TextField(blank=True, db_column='bank_ifsc', null=True)),
                ('id_proof', models.TextField(blank=True, db_column='id_proof', null=True)),
                ('pf_number', models.TextField(blank=True, db_column='pf_number', null=True)),
                ('esi_number', models.TextField(blank=True, db_column='esi_number', null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('join_date', models.TextField(blank=True, db_column='join_date', null=True)),
                ('password_hash', models.TextField(blank=True, db_column='password_hash', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('department', models.ForeignKey(blank=True, db_column='department_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='api.department')),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField()),
                ('present', models.BooleanField(default=True)),
                ('hours_worked', models.DecimalField(blank=True, db_column='hours_worked', decimal_places=2, max_digits=4, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='api.employee')),
            ],
            options={
                'db_table': 'attendance',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('salary_range', models.TextField(blank=True, db_column='salary_range', null=True)),
                ('status', models.TextField(default='open')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('department', models.ForeignKey(blank=True, db_column='department_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='api.department')),
            ],
            options={
                'db_table': 'jobs',
            },
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('phone', models.TextField()),
                ('cover_letter', models.TextField(blank=True, db_column='cover_letter', null=True)),
                ('experience', models.TextField(blank=True, null=True)),
                ('status', models.TextField(default='applied')),
                ('interview_date', models.TextField(blank=True, db_column='interview_date', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('job', models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='api.job')),
            ],
            options={
                'db_table': 'applicants',
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(default='casual')),
                ('start_date', models.TextField(db_column='start_date')),
                ('end_date', models.TextField(db_column='end_date')),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.TextField(default='pending')),
                ('hr_comment', models.TextField(blank=True, db_column='hr_comment', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='api.employee')),
            ],
            options={
                'db_table': 'leave_requests',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(default='general')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(db_column='is_read', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.employee')),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
        migrations.CreateModel(
            name='SalaryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.TextField(default='monthly')),
                ('week_number', models.IntegerField(blank=True, db_column='week_number', null=True)),
                ('status', models.TextField(default='pending')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='salary_records', to='api.employee')),
            ],
            options={
                'db_table': 'salary_records',
            },
        ),
    ]
