# Generated by Django 5.2.14 on 2026-05-19 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('start_time', models.TimeField(db_column='start_time')),
                ('end_time', models.TimeField(db_column='end_time')),
                ('pay_amount', models.DecimalField(db_column='pay_amount', decimal_places=2, max_digits=8)),
                ('is_overtime', models.BooleanField(db_column='is_overtime', default=False)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'session_configs',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('punch_time', models.TimeField(db_column='punch_time')),
                ('punch_type', models.TextField(choices=[('IN', 'In'), ('OUT', 'Out')], db_column='punch_type')),
                ('source', models.TextField(default='manual')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='api.employee')),
            ],
            options={
                'db_table': 'attendance_logs',
                'ordering': ['date', 'punch_time'],
            },
        ),
        migrations.CreateModel(
            name='WorkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('session_name', models.TextField(db_column='session_name')),
                ('check_in', models.TimeField(db_column='check_in')),
                ('check_out', models.TimeField(db_column='check_out')),
                ('hours_worked', models.DecimalField(db_column='hours_worked', decimal_places=2, max_digits=5)),
                ('session_amount', models.DecimalField(db_column='session_amount', decimal_places=2, max_digits=8)),
                ('is_overtime', models.BooleanField(db_column='is_overtime', default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='work_sessions', to='api.employee')),
                ('session_config', models.ForeignKey(blank=True, db_column='session_config_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_sessions', to='api.sessionconfig')),
            ],
            options={
                'db_table': 'work_sessions',
                'ordering': ['date', 'check_in'],
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_mode', models.TextField(choices=[('monthly', 'Monthly'), ('session', 'Session-based')], db_column='salary_mode')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('week_number', models.IntegerField(blank=True, db_column='week_number', null=True)),
                ('total_working_days', models.IntegerField(db_column='total_working_days', default=0)),
                ('present_days', models.DecimalField(db_column='present_days', decimal_places=1, default=0, max_digits=5)),
                ('absent_days', models.DecimalField(db_column='absent_days', decimal_places=1, default=0, max_digits=5)),
                ('completed_sessions', models.IntegerField(db_column='completed_sessions', default=0)),
                ('ot_hours', models.DecimalField(db_column='ot_hours', decimal_places=2, default=0, max_digits=5)),
                ('ot_amount', models.DecimalField(db_column='ot_amount', decimal_places=2, default=0, max_digits=8)),
                ('base_salary', models.DecimalField(db_column='base_salary', decimal_places=2, max_digits=10)),
                ('gross_salary', models.DecimalField(db_column='gross_salary', decimal_places=2, max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('final_salary', models.DecimalField(db_column='final_salary', decimal_places=2, max_digits=10)),
                ('status', models.TextField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='api.employee')),
            ],
            options={
                'db_table': 'payrolls',
                'unique_together': {('employee', 'month', 'year', 'week_number')},
            },
        ),
    ]
