# Generated by Django 5.2.15 on 2026-06-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_department_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollsettings',
            name='esi_applicable_below',
            field=models.DecimalField(db_column='esi_applicable_below', decimal_places=2, default=21000, help_text='Staff: ESI applies only when full monthly salary is below this amount.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payrollsettings',
            name='esi_rate',
            field=models.DecimalField(db_column='esi_rate', decimal_places=2, default=0, help_text='Staff employee ESI % (e.g. 0.75). 0 = disabled.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='payrollsettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='payrollsettings',
            name='pay_day',
            field=models.IntegerField(db_column='pay_day', default=5, help_text='Day of month when salaries are disbursed.'),
        ),
        migrations.AlterField(
            model_name='payrollsettings',
            name='pf_rate',
            field=models.DecimalField(db_column='pf_rate', decimal_places=2, default=0, help_text='Staff employee PF % (e.g. 12). 0 = disabled.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='payrollsettings',
            name='prod_esi_applicable_below',
            field=models.DecimalField(db_column='prod_esi_applicable_below', decimal_places=2, default=21000, help_text='Production: ESI applies only when monthly-equivalent earnings are below this amount.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payrollsettings',
            name='prod_esi_rate',
            field=models.DecimalField(db_column='prod_esi_rate', decimal_places=2, default=0, help_text='Production employee ESI % (e.g. 0.75). 0 = disabled.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='payrollsettings',
            name='prod_pf_rate',
            field=models.DecimalField(db_column='prod_pf_rate', decimal_places=2, default=0, help_text='Production employee PF % (e.g. 12). 0 = disabled.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='payrollsettings',
            name='production_pay_type',
            field=models.TextField(db_column='production_pay_type', default='biweekly', help_text='biweekly or monthly'),
        ),
    ]
