# Generated by Django 5.2.15 on 2026-07-04 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_shift_punch_windows_shift_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='blood_group',
            field=models.TextField(blank=True, db_column='blood_group', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='initial_salary',
            field=models.DecimalField(blank=True, db_column='initial_salary', decimal_places=2, help_text='Salary at time of joining — baseline for increment tracking.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='attendance_mode',
            field=models.TextField(db_column='attendance_mode', default='strict'),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='prod_extra_end',
            field=models.TimeField(db_column='prod_extra_end', default='20:00'),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='prod_extra_start',
            field=models.TimeField(db_column='prod_extra_start', default='17:50'),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='prod_first_half_end',
            field=models.TimeField(db_column='prod_first_half_end', default='12:30'),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='prod_first_half_start',
            field=models.TimeField(db_column='prod_first_half_start', default='08:30'),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='prod_pf_ef_rules',
            field=models.JSONField(blank=True, db_column='prod_pf_ef_rules', default=list),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='prod_second_half_end',
            field=models.TimeField(db_column='prod_second_half_end', default='17:30'),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='prod_second_half_start',
            field=models.TimeField(db_column='prod_second_half_start', default='13:30'),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='simple_grace_minutes',
            field=models.IntegerField(db_column='simple_grace_minutes', default=15, help_text='Simple mode fallback grace when employee has no shift assigned.'),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='simple_half_shift_cutoff',
            field=models.TimeField(db_column='simple_half_shift_cutoff', default='13:30', help_text='Simple mode: first punch after this time = half shift.'),
        ),
        migrations.AlterField(
            model_name='advancerepayment',
            name='payment_method',
            field=models.TextField(choices=[('cash', 'Hand Cash'), ('gpay', 'GPay'), ('payroll', 'Payroll Deduction')], db_column='payment_method', default='payroll'),
        ),
        migrations.AlterField(
            model_name='dailyshiftlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='monthlyshiftsummary',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField(db_column='effective_date')),
                ('notes', models.TextField(blank=True, null=True)),
                ('promoted_by', models.TextField(blank=True, db_column='promoted_by', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='api.employee')),
                ('new_department', models.ForeignKey(blank=True, db_column='new_department_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.department')),
                ('new_designation', models.ForeignKey(blank=True, db_column='new_designation_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.designation')),
                ('previous_department', models.ForeignKey(blank=True, db_column='previous_department_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.department')),
                ('previous_designation', models.ForeignKey(blank=True, db_column='previous_designation_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.designation')),
            ],
            options={
                'db_table': 'promotions',
                'ordering': ['-effective_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalaryIncrement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_salary', models.DecimalField(db_column='previous_salary', decimal_places=2, max_digits=10)),
                ('new_salary', models.DecimalField(db_column='new_salary', decimal_places=2, max_digits=10)),
                ('percent', models.DecimalField(db_column='percent', decimal_places=2, help_text='Increment percentage applied (e.g. 10.00).', max_digits=6)),
                ('effective_date', models.DateField(db_column='effective_date')),
                ('notes', models.TextField(blank=True, null=True)),
                ('added_by', models.TextField(blank=True, db_column='added_by', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='increments', to='api.employee')),
            ],
            options={
                'db_table': 'salary_increments',
                'ordering': ['-effective_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceDayRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.TextField(choices=[('present', 'Present'), ('absent', 'Absent'), ('half_shift', 'Half Shift'), ('on_leave', 'On Leave'), ('holiday', 'Holiday')], default='absent')),
                ('is_late', models.BooleanField(db_column='is_late', default=False)),
                ('is_half_shift', models.BooleanField(db_column='is_half_shift', default=False)),
                ('early_leave', models.BooleanField(db_column='early_leave', default=False)),
                ('shifts_earned', models.DecimalField(db_column='shifts_earned', decimal_places=2, default=0, help_text='0.50 per half. Staff max 1.00, production max 1.50.', max_digits=3)),
                ('first_punch', models.TimeField(blank=True, db_column='first_punch', null=True)),
                ('last_punch', models.TimeField(blank=True, db_column='last_punch', null=True)),
                ('total_punches', models.IntegerField(db_column='total_punches', default=0)),
                ('computed_mode', models.TextField(blank=True, db_column='computed_mode', null=True)),
                ('source', models.TextField(default='auto')),
                ('override_by', models.TextField(blank=True, db_column='override_by', null=True)),
                ('override_note', models.TextField(blank=True, db_column='override_note', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_day_records', to='api.employee')),
            ],
            options={
                'db_table': 'attendance_day_records',
                'ordering': ['date'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
