# Generated by Django 5.2.15 on 2026-07-04 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_employee_blood_group_employee_initial_salary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('device_type', models.TextField(choices=[('aiface_mars', 'AiFace-Mars'), ('zkteco', 'ZKTeco'), ('essl', 'eSSL'), ('generic_http', 'Generic HTTP API'), ('other', 'Other')], db_column='device_type', default='aiface_mars')),
                ('host', models.TextField(blank=True, default='', help_text='IP address or hostname')),
                ('port', models.IntegerField(blank=True, null=True)),
                ('api_key', models.TextField(blank=True, db_column='api_key', default='')),
                ('connection_config', models.JSONField(blank=True, db_column='connection_config', default=dict)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('is_default', models.BooleanField(db_column='is_default', default=False)),
                ('last_synced_at', models.DateTimeField(blank=True, db_column='last_synced_at', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'biometric_devices',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='IdCardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.TextField(db_column='primary_color', default='#006496')),
                ('secondary_color', models.TextField(db_column='secondary_color', default='#4FB8F0')),
                ('text_color', models.TextField(db_column='text_color', default='#0f172a')),
                ('font_family', models.TextField(db_column='font_family', default='Hanken Grotesk')),
                ('background_style', models.TextField(db_column='background_style', default='gradient')),
                ('logo_position', models.TextField(db_column='logo_position', default='left')),
                ('corner_style', models.TextField(db_column='corner_style', default='rounded')),
                ('show_qr_on_back', models.BooleanField(db_column='show_qr_on_back', default=True)),
                ('footer_text', models.TextField(blank=True, db_column='footer_text', default='')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'idcard_settings',
            },
        ),
        migrations.AddField(
            model_name='departmentmanager',
            name='can_approve_attendance',
            field=models.BooleanField(db_column='can_approve_attendance', default=True),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='company_address',
            field=models.TextField(blank=True, db_column='company_address', default=''),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='company_email',
            field=models.TextField(blank=True, db_column='company_email', default=''),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='company_gstin',
            field=models.TextField(blank=True, db_column='company_gstin', default=''),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='company_name',
            field=models.TextField(db_column='company_name', default='UKTextiles'),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='company_pan',
            field=models.TextField(blank=True, db_column='company_pan', default=''),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='company_phone',
            field=models.TextField(blank=True, db_column='company_phone', default=''),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='company_registration',
            field=models.TextField(blank=True, db_column='company_registration', default=''),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='company_tagline',
            field=models.TextField(db_column='company_tagline', default='Garments Manufacturing Excellence'),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='company_website',
            field=models.TextField(blank=True, db_column='company_website', default=''),
        ),
        migrations.CreateModel(
            name='AttendanceOverrideRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('previous_values', models.JSONField(db_column='previous_values', default=dict)),
                ('requested_values', models.JSONField(db_column='requested_values', default=dict)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.TextField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending')),
                ('requested_by', models.TextField(blank=True, db_column='requested_by', null=True)),
                ('reviewed_by', models.TextField(blank=True, db_column='reviewed_by', null=True)),
                ('review_comment', models.TextField(blank=True, db_column='review_comment', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, db_column='reviewed_at', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_override_requests', to='api.employee')),
            ],
            options={
                'db_table': 'attendance_override_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
