# Generated by Django 5.2.15 on 2026-07-06 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_biometricdevice_idcardsettings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NightShiftRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('worked_until', models.TimeField(db_column='worked_until', help_text='Latest punch-out this rule covers (e.g. 22:30, or 02:30 next day).')),
                ('crosses_midnight', models.BooleanField(db_column='crosses_midnight', default=False, help_text='True when worked_until is an early-morning time of the NEXT day.')),
                ('allowed_first_punch', models.TimeField(db_column='allowed_first_punch', help_text='Next-day first punch allowed up to this time without penalty.')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
            ],
            options={
                'db_table': 'night_shift_rules',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='departmentmanager',
            name='can_approve_casual_leave',
            field=models.BooleanField(db_column='can_approve_casual_leave', default=True),
        ),
        migrations.CreateModel(
            name='CasualLeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='The single day of casual leave.')),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.TextField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending')),
                ('reviewed_by', models.TextField(blank=True, db_column='reviewed_by', null=True)),
                ('reviewer_role', models.TextField(blank=True, db_column='reviewer_role', null=True)),
                ('review_comment', models.TextField(blank=True, db_column='review_comment', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, db_column='reviewed_at', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='casual_leaves', to='api.employee')),
            ],
            options={
                'db_table': 'casual_leave_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NightShiftRelaxation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('night_date', models.DateField(db_column='night_date', help_text='The day the night shift started.')),
                ('relaxation_date', models.DateField(db_column='relaxation_date', help_text='Next day — allowance applies here.')),
                ('last_punch_out', models.TimeField(db_column='last_punch_out')),
                ('crossed_midnight', models.BooleanField(db_column='crossed_midnight', default=False)),
                ('allowed_until', models.TimeField(db_column='allowed_until')),
                ('reported_at', models.TimeField(blank=True, db_column='reported_at', null=True)),
                ('within_allowance', models.BooleanField(blank=True, db_column='within_allowance', null=True)),
                ('computed_at', models.DateTimeField(auto_now=True, db_column='computed_at')),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='night_relaxations', to='api.employee')),
                ('rule', models.ForeignKey(blank=True, db_column='rule_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relaxations', to='api.nightshiftrule')),
            ],
            options={
                'db_table': 'night_shift_relaxations',
                'ordering': ['-relaxation_date'],
                'unique_together': {('employee', 'relaxation_date')},
            },
        ),
    ]
