# Generated by Django 5.2.15 on 2026-07-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_nightshiftrule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionShiftConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punch1_time', models.TimeField(db_column='punch1_time', default='08:30', help_text='Arrival')),
                ('punch2_time', models.TimeField(db_column='punch2_time', default='12:45', help_text='Lunch out')),
                ('punch3_time', models.TimeField(db_column='punch3_time', default='13:30', help_text='Lunch return')),
                ('punch4_time', models.TimeField(db_column='punch4_time', default='20:00', help_text='Departure')),
                ('grace_minutes', models.IntegerField(db_column='grace_minutes', default=10)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'production_shift_config',
            },
        ),
        migrations.CreateModel(
            name='ProductionShiftSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField()),
                ('start_time', models.TimeField(db_column='start_time')),
                ('end_time', models.TimeField(db_column='end_time')),
                ('shift_value', models.DecimalField(db_column='shift_value', decimal_places=2, max_digits=4)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
            ],
            options={
                'db_table': 'production_shift_segments',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='salary_per_shift',
            field=models.DecimalField(blank=True, db_column='salary_per_shift', decimal_places=2, max_digits=8, null=True),
        ),
    ]
