# Generated by Django 5.2.15 on 2026-07-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_seed_production_shift_segments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='salary_mode',
            field=models.TextField(choices=[('monthly', 'Monthly'), ('session', 'Session-based'), ('shift', 'Shift-based (Production)')], db_column='salary_mode'),
        ),
    ]
