# Generated by Django 5.2.15 on 2026-07-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_payroll_salary_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollsettings',
            name='default_salary_per_shift',
            field=models.DecimalField(db_column='default_salary_per_shift', decimal_places=2, default=0, help_text='Pre-filled Salary Per Shift for new production employees. 0 = no default.', max_digits=8),
        ),
    ]
