# Generated by Django 5.2.15 on 2026-07-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_payrollsettings_default_salary_per_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollsettings',
            name='prod_pf_ef_enabled',
            field=models.BooleanField(db_column='prod_pf_ef_enabled', default=False),
        ),
    ]
