# Generated by Django 5.2.15 on 2026-07-08 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_payrollsettings_prod_pf_ef_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollsettings',
            name='simple_grace_minutes',
        ),
    ]
