# Generated by Django 5.2.15 on 2026-07-10 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_chatchannel_chatmessage_chatreaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HrLoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(db_index=True)),
                ('ip_address', models.TextField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
            ],
            options={
                'db_table': 'hr_login_attempts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['username', 'created_at'], name='hr_login_at_usernam_5b81e7_idx')],
            },
        ),
    ]
