# Generated by Django 5.2.15 on 2026-07-10 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_hrloginattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='sender_label',
            field=models.TextField(blank=True, db_column='sender_label', default=''),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='backup_directory',
            field=models.TextField(blank=True, db_column='backup_directory', default=''),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='night_shift_enabled',
            field=models.BooleanField(db_column='night_shift_enabled', default=True),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='prod_payroll_rules_enabled',
            field=models.BooleanField(db_column='prod_payroll_rules_enabled', default=False),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='staff_payroll_rules_enabled',
            field=models.BooleanField(db_column='staff_payroll_rules_enabled', default=False),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(blank=True, db_column='sender_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='api.employee'),
        ),
    ]
