# Generated by Django 5.2.15 on 2026-07-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_chatmessage_sender_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyshiftsummary',
            name='permission_overage_count',
            field=models.IntegerField(default=0),
        ),
    ]
