# Generated by Django 5.2.16 on 2026-07-17 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_add_push_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='code',
            field=models.TextField(blank=True, db_column='code', null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='is_head_office',
            field=models.BooleanField(db_column='is_head_office', default=False),
        ),
    ]
