# Generated by Django 5.2.16 on 2026-07-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_seed_head_office_backfill'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='next_employee_seq',
            field=models.IntegerField(db_column='next_employee_seq', default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='unit_code',
            field=models.TextField(blank=True, db_column='unit_code', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='code',
            field=models.TextField(blank=True, db_column='code', null=True, unique=True),
        ),
    ]
