# Generated by Django 5.2.15 on 2026-07-18 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_backfill_unit_codes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDocumentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.TextField(choices=[('offer_letter', 'Offer Letter'), ('experience_letter', 'Experience Letter'), ('salary_slip', 'Salary Slip')], db_column='doc_type', unique=True)),
                ('primary_color', models.TextField(db_column='primary_color', default='#0E4B3A')),
                ('accent_color', models.TextField(db_column='accent_color', default='#C9A227')),
                ('heading_style', models.TextField(db_column='heading_style', default='serif')),
                ('show_watermark', models.BooleanField(db_column='show_watermark', default=True)),
                ('footer_tagline', models.TextField(blank=True, db_column='footer_tagline', default='Weaving Quality. Building Trust.')),
                ('logo_override', models.TextField(blank=True, db_column='logo_override', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'company_document_settings',
            },
        ),
    ]
