# Generated by Django 5.2.16 on 2026-07-20 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_company_document_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydocumentsettings',
            name='doc_type',
            field=models.TextField(choices=[('offer_letter', 'Offer Letter'), ('experience_letter', 'Experience Letter'), ('salary_slip', 'Salary Slip'), ('resignation_letter', 'Resignation Letter')], db_column='doc_type', unique=True),
        ),
    ]
