# Generated by Django 5.2.15 on 2026-07-20 05:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_companydocumentsettings_doc_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionshiftconfig',
            name='punch1_time',
            field=models.TimeField(db_column='punch1_time', default=datetime.time(8, 30), help_text='Arrival'),
        ),
        migrations.AlterField(
            model_name='productionshiftconfig',
            name='punch2_time',
            field=models.TimeField(db_column='punch2_time', default=datetime.time(12, 45), help_text='Lunch out'),
        ),
        migrations.AlterField(
            model_name='productionshiftconfig',
            name='punch3_time',
            field=models.TimeField(db_column='punch3_time', default=datetime.time(13, 30), help_text='Lunch return'),
        ),
        migrations.AlterField(
            model_name='productionshiftconfig',
            name='punch4_time',
            field=models.TimeField(db_column='punch4_time', default=datetime.time(20, 0), help_text='Departure'),
        ),
    ]
