# Generated by Django 5.2.15 on 2026-07-20 06:46
#
# Removes duplicate AttendanceLog rows (same employee/date/punch_time/punch_type
# with no DB-level uniqueness ever enforced — 28 pairs found in production, all
# from a single overlapping biometric sync on 2026-05-12) and adds the missing
# unique constraint so get_or_create() in biometric_sync.py can never create new
# duplicates again. Existing duplicates were crashing every subsequent sync with
# AttendanceLog.MultipleObjectsReturned the moment it revisited one of those rows,
# aborting the whole device sync partway through.

from django.db import migrations, models


def dedupe_attendance_logs(apps, schema_editor):
    AttendanceLog = apps.get_model("api", "AttendanceLog")
    seen = {}
    duplicate_ids = []
    for log in AttendanceLog.objects.order_by("id").only(
        "id", "employee_id", "date", "punch_time", "punch_type"
    ):
        key = (log.employee_id, log.date, log.punch_time, log.punch_type)
        if key in seen:
            duplicate_ids.append(log.id)
        else:
            seen[key] = log.id
    if duplicate_ids:
        AttendanceLog.objects.filter(id__in=duplicate_ids).delete()


def noop_reverse(apps, schema_editor):
    pass  # deleted duplicate rows are not recreated on reverse — nothing to do


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_fix_production_shift_config_time_defaults'),
    ]

    operations = [
        migrations.RunPython(dedupe_attendance_logs, noop_reverse),
        migrations.AlterUniqueTogether(
            name='attendancelog',
            unique_together={('employee', 'date', 'punch_time', 'punch_type')},
        ),
    ]
