# Generated by Django 5.2.15 on 2026-07-20
#
# Same incident as 0042 (overlapping biometric sync on 2026-05-12) produced 22
# duplicate Attendance rows (same employee/date, no DB-level uniqueness ever
# enforced). Any subsequent sync revisiting one of those days crashed with
# Attendance.MultipleObjectsReturned via update_or_create(), aborting the whole
# device sync partway through — dedupe + add the missing unique constraint.

from django.db import migrations


def dedupe_attendance(apps, schema_editor):
    Attendance = apps.get_model("api", "Attendance")
    seen = {}
    duplicate_ids = []
    for rec in Attendance.objects.order_by("id").only("id", "employee_id", "date"):
        key = (rec.employee_id, rec.date)
        if key in seen:
            duplicate_ids.append(rec.id)
        else:
            seen[key] = rec.id
    if duplicate_ids:
        Attendance.objects.filter(id__in=duplicate_ids).delete()


def noop_reverse(apps, schema_editor):
    pass  # deleted duplicate rows are not recreated on reverse — nothing to do


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_dedupe_and_constrain_attendance_log'),
    ]

    operations = [
        migrations.RunPython(dedupe_attendance, noop_reverse),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('employee', 'date')},
        ),
    ]
