# Generated by Django 5.2.16 on 2026-07-21 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_dedupe_and_constrain_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiringRuleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('required_skills', models.JSONField(blank=True, db_column='required_skills', default=list)),
                ('education_qualification', models.TextField(blank=True, db_column='education_qualification', null=True)),
                ('min_experience_years', models.DecimalField(db_column='min_experience_years', decimal_places=1, default=0, max_digits=4)),
                ('preferred_city', models.TextField(blank=True, db_column='preferred_city', null=True)),
                ('other_requirements', models.TextField(blank=True, db_column='other_requirements', null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('department', models.ForeignKey(db_column='department_id', on_delete=django.db.models.deletion.CASCADE, related_name='hiring_rule_sets', to='api.department')),
            ],
            options={
                'db_table': 'hiring_rule_sets',
            },
        ),
        migrations.CreateModel(
            name='ScreeningCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_file', models.FileField(db_column='resume_file', upload_to='resumes/%Y/%m/')),
                ('original_filename', models.TextField(db_column='original_filename')),
                ('source', models.TextField(db_column='source', default='single')),
                ('candidate_name', models.TextField(blank=True, db_column='candidate_name', null=True)),
                ('email', models.TextField(blank=True, db_column='email', null=True)),
                ('phone', models.TextField(blank=True, db_column='phone', null=True)),
                ('city', models.TextField(blank=True, db_column='city', null=True)),
                ('extracted_skills', models.JSONField(blank=True, db_column='extracted_skills', default=list)),
                ('extracted_experience_years', models.DecimalField(blank=True, db_column='extracted_experience_years', decimal_places=1, max_digits=4, null=True)),
                ('extracted_education', models.TextField(blank=True, db_column='extracted_education', null=True)),
                ('raw_text_excerpt', models.TextField(blank=True, db_column='raw_text_excerpt', null=True)),
                ('match_score', models.DecimalField(blank=True, db_column='match_score', decimal_places=2, max_digits=5, null=True)),
                ('score_breakdown', models.JSONField(blank=True, db_column='score_breakdown', null=True)),
                ('rank_in_batch', models.IntegerField(blank=True, db_column='rank_in_batch', null=True)),
                ('status', models.TextField(db_column='status', default='uploaded')),
                ('screened_at', models.DateTimeField(blank=True, db_column='screened_at', null=True)),
                ('interview_invited_at', models.DateTimeField(blank=True, db_column='interview_invited_at', null=True)),
                ('interview_datetime', models.DateTimeField(blank=True, db_column='interview_datetime', null=True)),
                ('rejection_emailed_at', models.DateTimeField(blank=True, db_column='rejection_emailed_at', null=True)),
                ('notes', models.TextField(blank=True, db_column='notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('department', models.ForeignKey(blank=True, db_column='department_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screening_candidates', to='api.department')),
                ('rule_set', models.ForeignKey(db_column='rule_set_id', on_delete=django.db.models.deletion.PROTECT, related_name='candidates', to='api.hiringruleset')),
            ],
            options={
                'db_table': 'screening_candidates',
            },
        ),
    ]
