# Generated by Django 5.2.16 on 2026-07-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_hiringruleset_screeningcandidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiringruleset',
            name='soft_skills',
            field=models.JSONField(blank=True, db_column='soft_skills', default=list),
        ),
        migrations.AddField(
            model_name='screeningcandidate',
            name='extracted_soft_skills',
            field=models.JSONField(blank=True, db_column='extracted_soft_skills', default=list),
        ),
    ]
