# Generated by Django 5.2.15 on 2026-07-21 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_hiringruleset_soft_skills_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField(choices=[('pan_card', 'PAN Card'), ('aadhaar_card', 'Aadhaar Card'), ('educational_certificate', 'Educational Certificates'), ('voter_id_or_birth_certificate', 'Voter ID or Birth Certificate'), ('bank_passbook', 'Bank Passbook'), ('offer_letter', 'Offer Letter'), ('experience_letter', 'Experience Letter'), ('resignation_letter', 'Resignation Letter'), ('staff_letter', 'Staff Letter'), ('production_employee_documents', 'Production Employee Documents')], db_column='category')),
                ('file', models.FileField(db_column='file', upload_to='employee_documents/%Y/%m/')),
                ('original_filename', models.TextField(db_column='original_filename')),
                ('uploaded_by', models.TextField(blank=True, db_column='uploaded_by', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_column='uploaded_at')),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.employee')),
            ],
            options={
                'db_table': 'employee_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
