# Generated by Django 5.2.15 on 2026-07-23 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_employeedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='geofence_lat',
            field=models.DecimalField(blank=True, db_column='geofence_lat', decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='geofence_lng',
            field=models.DecimalField(blank=True, db_column='geofence_lng', decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='geofence_radius_m',
            field=models.IntegerField(blank=True, db_column='geofence_radius_m', default=200, null=True),
        ),
        migrations.AddField(
            model_name='departmentmanager',
            name='can_approve_geo_punch',
            field=models.BooleanField(db_column='can_approve_geo_punch', default=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='location_tracking_enabled',
            field=models.BooleanField(db_column='location_tracking_enabled', default=False),
        ),
        migrations.CreateModel(
            name='GeoPunchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punch_date', models.DateField(db_column='punch_date')),
                ('punch_time', models.TimeField(db_column='punch_time')),
                ('punch_type', models.TextField(choices=[('IN', 'In'), ('OUT', 'Out')], db_column='punch_type')),
                ('latitude', models.DecimalField(db_column='latitude', decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(db_column='longitude', decimal_places=6, max_digits=9)),
                ('accuracy_m', models.FloatField(blank=True, db_column='accuracy_m', null=True)),
                ('distance_m', models.FloatField(db_column='distance_m')),
                ('is_mocked', models.BooleanField(db_column='is_mocked', default=False)),
                ('photo1', models.FileField(db_column='photo1', upload_to='geo_punch_requests/%Y/%m/')),
                ('photo2', models.FileField(db_column='photo2', upload_to='geo_punch_requests/%Y/%m/')),
                ('status', models.TextField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending')),
                ('reviewed_by', models.TextField(blank=True, db_column='reviewed_by', null=True)),
                ('review_comment', models.TextField(blank=True, db_column='review_comment', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, db_column='reviewed_at', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('branch', models.ForeignKey(blank=True, db_column='branch_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.branch')),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='geo_punch_requests', to='api.employee')),
            ],
            options={
                'db_table': 'geo_punch_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveLocationPing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(db_column='latitude', decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(db_column='longitude', decimal_places=6, max_digits=9)),
                ('accuracy_m', models.FloatField(blank=True, db_column='accuracy_m', null=True)),
                ('is_mocked', models.BooleanField(db_column='is_mocked', default=False)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_column='recorded_at')),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='location_pings', to='api.employee')),
            ],
            options={
                'db_table': 'live_location_pings',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['employee', '-recorded_at'], name='live_locati_employe_df81ee_idx')],
            },
        ),
    ]
