# Generated by Django 5.2.15 on 2026-07-23 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_branch_geofence_lat_branch_geofence_lng_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentmanager',
            name='can_approve_geo_punch',
        ),
        migrations.AddField(
            model_name='departmentmanager',
            name='can_approve_on_duty',
            field=models.BooleanField(db_column='can_approve_on_duty', default=True),
        ),
        migrations.CreateModel(
            name='OnDutyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punch_date', models.DateField(db_column='punch_date')),
                ('punch_time', models.TimeField(db_column='punch_time')),
                ('punch_type', models.TextField(choices=[('IN', 'In'), ('OUT', 'Out')], db_column='punch_type')),
                ('reason', models.TextField()),
                ('latitude', models.DecimalField(db_column='latitude', decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(db_column='longitude', decimal_places=6, max_digits=9)),
                ('accuracy_m', models.FloatField(blank=True, db_column='accuracy_m', null=True)),
                ('is_mocked', models.BooleanField(db_column='is_mocked', default=False)),
                ('photo1', models.FileField(db_column='photo1', upload_to='on_duty_requests/%Y/%m/')),
                ('photo2', models.FileField(db_column='photo2', upload_to='on_duty_requests/%Y/%m/')),
                ('status', models.TextField(choices=[('pending_hod', 'Pending HOD Approval'), ('pending_hr', 'Pending HR Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_hod')),
                ('hod_reviewed_by', models.TextField(blank=True, db_column='hod_reviewed_by', null=True)),
                ('hod_review_comment', models.TextField(blank=True, db_column='hod_review_comment', null=True)),
                ('hod_reviewed_at', models.DateTimeField(blank=True, db_column='hod_reviewed_at', null=True)),
                ('hr_reviewed_by', models.TextField(blank=True, db_column='hr_reviewed_by', null=True)),
                ('hr_review_comment', models.TextField(blank=True, db_column='hr_review_comment', null=True)),
                ('hr_reviewed_at', models.DateTimeField(blank=True, db_column='hr_reviewed_at', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('branch', models.ForeignKey(blank=True, db_column='branch_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.branch')),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='on_duty_requests', to='api.employee')),
            ],
            options={
                'db_table': 'on_duty_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='GeoPunchRequest',
        ),
    ]
