# Generated by Django 5.2.15 on 2026-07-24 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_remove_departmentmanager_can_approve_geo_punch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnDutySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.TextField()),
                ('status', models.TextField(choices=[('pending_hod', 'Pending HOD Approval'), ('pending_hr', 'Pending HR Approval'), ('active', 'Active'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending_hod')),
                ('hod_reviewed_by', models.TextField(blank=True, db_column='hod_reviewed_by', null=True)),
                ('hod_review_comment', models.TextField(blank=True, db_column='hod_review_comment', null=True)),
                ('hod_reviewed_at', models.DateTimeField(blank=True, db_column='hod_reviewed_at', null=True)),
                ('hr_reviewed_by', models.TextField(blank=True, db_column='hr_reviewed_by', null=True)),
                ('hr_review_comment', models.TextField(blank=True, db_column='hr_review_comment', null=True)),
                ('hr_reviewed_at', models.DateTimeField(blank=True, db_column='hr_reviewed_at', null=True)),
                ('started_at', models.DateTimeField(blank=True, db_column='started_at', null=True)),
                ('completed_at', models.DateTimeField(blank=True, db_column='completed_at', null=True)),
                ('completed_by', models.TextField(blank=True, db_column='completed_by', null=True)),
                ('completion_reason', models.TextField(blank=True, choices=[('manual', 'Manual — Employee Marked Done'), ('auto_4th_punch', 'Automatic — 4th Punch Approved')], db_column='completion_reason', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('branch', models.ForeignKey(blank=True, db_column='branch_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.branch')),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='on_duty_sessions', to='api.employee')),
            ],
            options={
                'db_table': 'on_duty_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnDutyPunchVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punch_date', models.DateField(db_column='punch_date')),
                ('punch_time', models.TimeField(db_column='punch_time')),
                ('punch_type', models.TextField(choices=[('IN', 'In'), ('OUT', 'Out')], db_column='punch_type')),
                ('punch_number', models.IntegerField(db_column='punch_number')),
                ('latitude', models.DecimalField(db_column='latitude', decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(db_column='longitude', decimal_places=6, max_digits=9)),
                ('accuracy_m', models.FloatField(blank=True, db_column='accuracy_m', null=True)),
                ('is_mocked', models.BooleanField(db_column='is_mocked', default=False)),
                ('photo', models.FileField(db_column='photo', upload_to='on_duty_punch_verifications/%Y/%m/')),
                ('status', models.TextField(choices=[('pending', 'Pending HR Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending')),
                ('hr_reviewed_by', models.TextField(blank=True, db_column='hr_reviewed_by', null=True)),
                ('hr_review_comment', models.TextField(blank=True, db_column='hr_review_comment', null=True)),
                ('hr_reviewed_at', models.DateTimeField(blank=True, db_column='hr_reviewed_at', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='on_duty_punch_verifications', to='api.employee')),
                ('session', models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, related_name='punch_verifications', to='api.ondutysession')),
            ],
            options={
                'db_table': 'on_duty_punch_verifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='OnDutyRequest',
        ),
    ]
