# Generated by Django 5.2.15 on 2026-07-25 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_attendancedayrecord_primary_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollsettings',
            name='shift_punctuality_window_minutes',
            field=models.IntegerField(db_column='shift_punctuality_window_minutes', default=60, help_text="Staff only. Even with a first+last punch pair, Full Shift also requires the first punch within this many minutes of the employee's assigned shift start time, and the last punch within the same window of the assigned shift end time -otherwise the day is capped at Half Shift, regardless of any approved Permission. Employees with no assigned shift have no reference to check against, so this never applies to them."),
        ),
    ]
