# Generated by Django 5.2.15 on 2026-07-27 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_payrollsettings_first_punch_pre_shift_buffer_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentmanager',
            name='can_approve_missing_punch',
            field=models.BooleanField(db_column='can_approve_missing_punch', default=True),
        ),
        migrations.AddField(
            model_name='employeepermission',
            name='approver_role',
            field=models.TextField(blank=True, db_column='approver_role', null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='approver_role',
            field=models.TextField(blank=True, db_column='approver_role', null=True),
        ),
        migrations.CreateModel(
            name='MissingPunchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('punch_time', models.TimeField(db_column='punch_time')),
                ('punch_type', models.TextField(choices=[('IN', 'In'), ('OUT', 'Out')], db_column='punch_type')),
                ('reason', models.TextField()),
                ('status', models.TextField(choices=[('pending_hod', 'Pending HOD Approval'), ('pending_hr', 'Pending HR Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_hod')),
                ('hod_reviewed_by', models.TextField(blank=True, db_column='hod_reviewed_by', null=True)),
                ('hod_review_comment', models.TextField(blank=True, db_column='hod_review_comment', null=True)),
                ('hod_reviewed_at', models.DateTimeField(blank=True, db_column='hod_reviewed_at', null=True)),
                ('hr_reviewed_by', models.TextField(blank=True, db_column='hr_reviewed_by', null=True)),
                ('hr_review_comment', models.TextField(blank=True, db_column='hr_review_comment', null=True)),
                ('hr_reviewed_at', models.DateTimeField(blank=True, db_column='hr_reviewed_at', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='missing_punch_requests', to='api.employee')),
            ],
            options={
                'db_table': 'missing_punch_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
