# Generated by Django 5.2.15 on 2026-07-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_departmentmanager_can_approve_missing_punch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingpunchrequest',
            name='punch_slot',
            field=models.TextField(blank=True, choices=[('morning_in', 'Morning Check-In'), ('lunch_out', 'Lunch Check-Out'), ('lunch_in', 'Lunch Check-In'), ('evening_out', 'Evening Check-Out')], db_column='punch_slot', null=True),
        ),
    ]
