# Generated by Django 5.2.15 on 2026-07-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_missingpunchrequest_punch_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoSyncRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='')),
                ('time', models.TimeField(help_text='Time of day (Asia/Kolkata) this rule fires')),
                ('days_of_week', models.TextField(default='*')),
                ('device_selection', models.JSONField(blank=True, default=list)),
                ('mode', models.TextField(choices=[('day', 'Today'), ('week', 'Last One Week'), ('month', 'Last One Month'), ('all', 'All Records')], default='day')),
                ('is_enabled', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_status', models.TextField(blank=True, null=True)),
                ('last_run_summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'auto_sync_rules',
                'ordering': ['time'],
            },
        ),
    ]
