# Generated by Django 5.2.15 on 2026-07-31 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_auto_sync_rule'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupDriveConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('folder_id', models.TextField(blank=True, default='')),
                ('service_account_json', models.TextField(blank=True, default='')),
                ('last_upload_at', models.DateTimeField(blank=True, null=True)),
                ('last_upload_status', models.TextField(blank=True, null=True)),
                ('last_upload_summary', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'backup_drive_config',
            },
        ),
        migrations.CreateModel(
            name='BackupSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('time', models.TimeField(default='02:00', help_text='Time of day (Asia/Kolkata) this fires')),
                ('days_of_week', models.TextField(default='*')),
                ('retention_count', models.IntegerField(default=14)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_status', models.TextField(blank=True, null=True)),
                ('last_run_summary', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'backup_schedule',
            },
        ),
        migrations.AlterModelOptions(
            name='hrloginattempt',
            options={},
        ),
    ]
