# Generated by Django 5.2.15 on 2026-08-01 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_backup_schedule_and_drive_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.TextField(db_index=True, unique=True)),
                ('device_label', models.TextField(blank=True, default='')),
                ('user_agent', models.TextField(blank=True, default='')),
                ('ip_address', models.TextField(blank=True, db_column='ip_address', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('last_seen_at', models.DateTimeField(auto_now_add=True, db_column='last_seen_at')),
                ('revoked_at', models.DateTimeField(blank=True, db_column='revoked_at', null=True)),
                ('hr_user', models.ForeignKey(db_column='hr_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='login_sessions', to='api.hruser')),
            ],
            options={
                'db_table': 'login_sessions',
                'indexes': [models.Index(fields=['hr_user', 'revoked_at'], name='login_sessi_hr_user_bd3754_idx')],
            },
        ),
    ]
