# Generated by Django 5.2.15 on 2026-08-07 05:15

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_login_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollsettings',
            name='default_shift_end_time',
            field=models.TimeField(db_column='default_shift_end_time', default='17:30'),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='default_shift_first_half_end',
            field=models.TimeField(db_column='default_shift_first_half_end', default='13:30'),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='default_shift_grace_minutes',
            field=models.IntegerField(db_column='default_shift_grace_minutes', default=15),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='default_shift_lunch_duration_minutes',
            field=models.IntegerField(db_column='default_shift_lunch_duration_minutes', default=60),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='default_shift_lunch_grace_minutes',
            field=models.IntegerField(db_column='default_shift_lunch_grace_minutes', default=10),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='default_shift_start_time',
            field=models.TimeField(db_column='default_shift_start_time', default='08:30'),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='half_shift_late_reference_time',
            field=models.TimeField(db_column='half_shift_late_reference_time', default='14:30', help_text='Staff only. On a Half Shift day, the first punch is flagged Late only if it is strictly after this time. Compared at minute granularity (seconds ignored).'),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='late_deduction_slabs',
            field=models.JSONField(blank=True, db_column='late_deduction_slabs', default=api.models._default_late_deduction_slabs, help_text='Shift deduction thresholds. Each row: fromLates (billable late count reached) -> deductionShifts (shifts cut). Highest matching row wins; the last row holds for anything beyond it.'),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='late_free_allowance',
            field=models.IntegerField(db_column='late_free_allowance', default=3, help_text='Free lates + permissions allowed per employee per month before any shift deduction applies. Lates and approved Permission requests draw on this same shared pool.'),
        ),
    ]
