# Generated by Django 5.2.15 on 2026-08-07 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_attendance_late_policy_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollsettings',
            name='default_shift_end_time',
        ),
        migrations.RemoveField(
            model_name='payrollsettings',
            name='default_shift_start_time',
        ),
    ]
