# Generated by Django 5.2.15 on 2026-08-07 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_remove_default_shift_start_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancedayrecord',
            name='early_out_without_permission',
            field=models.BooleanField(db_column='early_out_without_permission', default=False),
        ),
        migrations.AddField(
            model_name='attendancedayrecord',
            name='late_in_without_permission',
            field=models.BooleanField(db_column='late_in_without_permission', default=False),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='without_permission_deduction_slabs',
            field=models.JSONField(blank=True, db_column='without_permission_deduction_slabs', default=list, help_text='Same shape/semantics as late_deduction_slabs, applied to the Without Permission pool instead. Empty by default -no deduction until HR configures rows here.'),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='without_permission_free_allowance',
            field=models.IntegerField(db_column='without_permission_free_allowance', default=0, help_text='Free late-in/early-out-without-permission occurrences allowed per employee per month before any shift deduction applies.'),
        ),
    ]
