# Generated by Django 5.2.15 on 2026-08-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_without_permission_detection'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancedayrecord',
            name='late_reason',
            field=models.TextField(blank=True, db_column='late_reason', null=True),
        ),
    ]
