# Generated by Django 5.2.15 on 2026-08-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_attendance_day_record_late_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='period_end',
            field=models.DateField(blank=True, db_column='period_end', null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='period_start',
            field=models.DateField(blank=True, db_column='period_start', null=True),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='prod_period_anchor_date',
            field=models.DateField(blank=True, db_column='prod_period_anchor_date', help_text='Start date of the first period for weekday_anchored/custom_recurring styles. Ignored for calendar_month.', null=True),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='prod_period_custom_days',
            field=models.IntegerField(blank=True, db_column='prod_period_custom_days', help_text='Fixed day-length of each period. Only used when prod_period_style = custom_recurring.', null=True),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='prod_period_frequency',
            field=models.TextField(choices=[('weekly', 'Weekly'), ('2weeks', '2 Weeks'), ('3weeks', '3 Weeks'), ('monthly', 'Monthly')], db_column='prod_period_frequency', default='2weeks', help_text='How often production payroll periods repeat.'),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='prod_period_style',
            field=models.TextField(choices=[('calendar_month', 'Calendar Month Anchored'), ('weekday_anchored', 'Weekday Anchored (Rolling)'), ('custom_recurring', 'Custom Recurring')], db_column='prod_period_style', default='calendar_month', help_text='How period boundaries are anchored. Monthly frequency is only valid with calendar_month style.'),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='prod_period_weekday_anchor',
            field=models.TextField(blank=True, choices=[('mon_sat', 'Monday–Saturday'), ('sun_sat', 'Sunday–Saturday')], db_column='prod_period_weekday_anchor', help_text='Only used when prod_period_style = weekday_anchored.', null=True),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='period_end',
            field=models.DateField(blank=True, db_column='period_end', null=True),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='period_start',
            field=models.DateField(blank=True, db_column='period_start', null=True),
        ),
        migrations.AddConstraint(
            model_name='payroll',
            constraint=models.UniqueConstraint(condition=models.Q(('period_start__isnull', False)), fields=('employee', 'period_start', 'period_end'), name='uniq_payroll_employee_period'),
        ),
        migrations.AddConstraint(
            model_name='salaryslip',
            constraint=models.UniqueConstraint(condition=models.Q(('period_start__isnull', False)), fields=('employee', 'period_start', 'period_end'), name='uniq_salary_slip_employee_period'),
        ),
    ]
