# Generated by Django 5.2.15 on 2026-08-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_production_payroll_periods'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollsettings',
            name='prod_attendance_mode',
            field=models.TextField(choices=[('simple', 'Simple'), ('strict', 'Strict')], db_column='prod_attendance_mode', default='strict', help_text="Governs the Production Late Detection check below only -does not affect shifts-earned/pay math. Simple: late if the day's first punch is after (assigned shift start + grace). Strict: also flags leaving before (assigned shift end - grace) as late."),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='prod_late_deduction_slabs',
            field=models.JSONField(blank=True, db_column='prod_late_deduction_slabs', default=list, help_text='Same shape/semantics as late_deduction_slabs (staff), applied to the Production Late pool instead. Empty by default -no deduction until HR configures rows here.'),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='prod_late_detection_enabled',
            field=models.BooleanField(db_column='prod_late_detection_enabled', default=False, help_text='Off by default -production payroll ignores lateness entirely until enabled.'),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='prod_late_free_allowance',
            field=models.IntegerField(db_column='prod_late_free_allowance', default=3, help_text='Free late occurrences allowed per employee per period before any shift deduction applies.'),
        ),
    ]
