# Generated by Django 5.2.16 on 2026-08-19 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_production_late_detection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupschedule',
            name='time',
            field=models.TimeField(default=datetime.time(2, 0), help_text='Time of day (Asia/Kolkata) this fires'),
        ),
    ]
