# Generated by Django 5.2.16 on 2026-08-19 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_alter_backupschedule_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppMessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.TextField(db_column='document_type', unique=True)),
                ('meta_template_name', models.TextField(blank=True, db_column='meta_template_name', default='')),
                ('meta_language_code', models.TextField(db_column='meta_language_code', default='en')),
                ('variable_note', models.TextField(blank=True, db_column='variable_note', default='', help_text="Human-readable note on what each {{n}} in the template maps to, e.g. '{{1}}=employee name, {{2}}=month/year'.")),
                ('is_enabled', models.BooleanField(db_column='is_enabled', default=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'whatsapp_message_template',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.TextField(choices=[('salary_slip', 'Salary Slip'), ('id_card', 'ID Card'), ('offer_letter', 'Offer Letter'), ('experience_letter', 'Experience Letter'), ('resignation_letter', 'Resignation Letter'), ('other', 'Other Document')], db_column='document_type')),
                ('document_ref_id', models.IntegerField(blank=True, db_column='document_ref_id', null=True)),
                ('phone_number', models.TextField(db_column='phone_number')),
                ('status', models.TextField(db_column='status', default='sent')),
                ('meta_message_id', models.TextField(blank=True, db_column='meta_message_id', default='')),
                ('error_message', models.TextField(blank=True, db_column='error_message', default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_messages', to='api.employee')),
                ('sent_by', models.ForeignKey(blank=True, db_column='sent_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages_sent', to='api.hruser')),
            ],
            options={
                'db_table': 'whatsapp_message_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee', 'document_type'], name='whatsapp_me_employe_0315a4_idx')],
            },
        ),
    ]
