# Generated by Django 5.2.16 on 2026-08-24 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_whatsappmessagetemplate_whatsappmessagelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='last_mobile_login_at',
            field=models.DateTimeField(blank=True, db_column='last_mobile_login_at', null=True),
        ),
    ]
