# Generated by Django 5.2.16 on 2026-08-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_employee_last_mobile_login_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollsettings',
            name='theme_custom',
            field=models.JSONField(blank=True, db_column='theme_custom', default=dict),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='theme_name',
            field=models.TextField(db_column='theme_name', default='default'),
        ),
    ]
