# Generated by Django 5.2.16 on 2026-08-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_payrollsettings_theme_custom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biometricdevice',
            name='last_push_at',
            field=models.DateTimeField(blank=True, db_column='last_push_at', null=True),
        ),
        migrations.AddField(
            model_name='biometricdevice',
            name='serial_number',
            field=models.TextField(blank=True, db_column='serial_number', default=''),
        ),
        migrations.CreateModel(
            name='UnmatchedPunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_user_id', models.TextField(db_column='device_user_id', db_index=True)),
                ('device_label', models.TextField(blank=True, db_column='device_label', default='')),
                ('device_serial', models.TextField(blank=True, db_column='device_serial', default='')),
                ('punch_count', models.IntegerField(db_column='punch_count', default=0)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True, db_column='first_seen_at')),
                ('last_seen_at', models.DateTimeField(auto_now=True, db_column='last_seen_at')),
                ('last_punch_date', models.DateField(blank=True, db_column='last_punch_date', null=True)),
                ('last_punch_time', models.TimeField(blank=True, db_column='last_punch_time', null=True)),
                ('resolved', models.BooleanField(db_column='resolved', default=False)),
                ('resolved_note', models.TextField(blank=True, db_column='resolved_note', default='')),
            ],
            options={
                'db_table': 'unmatched_punches',
                'ordering': ['-last_seen_at'],
                'unique_together': {('device_user_id', 'device_serial')},
            },
        ),
    ]
