# Generated by Django 5.2.16 on 2026-08-28 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_backfill_device_serials'),
    ]

    operations = [
        migrations.AddField(
            model_name='ondutysession',
            name='employee_ended_at',
            field=models.DateTimeField(blank=True, db_column='employee_ended_at', null=True),
        ),
    ]
