# Generated by Django 5.2.16 on 2026-08-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_on_duty_employee_ended_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ondutysession',
            name='completion_reason',
            field=models.TextField(blank=True, choices=[('manual', 'Manual -Employee Marked Done'), ('auto_4th_punch', 'Automatic -All 4 Punches Recorded'), ('auto_day_end', 'Automatic -Day Ended (11 PM)')], db_column='completion_reason', null=True),
        ),
    ]
