# Generated by Django 5.2.15 on 2026-08-31 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_on_duty_completion_reason_day_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='hruser',
            name='is_hidden',
            field=models.BooleanField(db_column='is_hidden', default=False, help_text='Hide from the Account Management list. Does NOT disable the account.'),
        ),
        migrations.AddField(
            model_name='hruser',
            name='master_features',
            field=models.JSONField(blank=True, db_column='master_features', default=dict),
        ),
    ]
