# Generated by Django 5.2.15 on 2026-09-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_hruser_is_hidden_hruser_master_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.TextField(),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('name', 'branch'), name='uniq_department_name_per_branch'),
        ),
    ]
