# Generated by Django 5.2.15 on 2026-09-01 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_alter_department_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='branch',
            field=models.ForeignKey(blank=True, db_column='branch_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='api.branch'),
        ),
        migrations.AddField(
            model_name='chatchannel',
            name='branch',
            field=models.ForeignKey(blank=True, db_column='branch_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_channels', to='api.branch'),
        ),
        migrations.AddField(
            model_name='shifttemplate',
            name='branch',
            field=models.ForeignKey(blank=True, db_column='branch_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_templates', to='api.branch'),
        ),
        migrations.AddConstraint(
            model_name='chatchannel',
            constraint=models.UniqueConstraint(condition=models.Q(('channel_type', 'company')), fields=('branch',), name='unique_company_chat_channel_per_branch'),
        ),
        migrations.AddConstraint(
            model_name='chatchannel',
            constraint=models.UniqueConstraint(condition=models.Q(('branch__isnull', True), ('channel_type', 'company')), fields=('channel_type',), name='unique_legacy_company_chat_channel'),
        ),
    ]
