# Generated by Django 5.2.15 on 2026-09-01 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_auditlog_branch_chatchannel_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchSettingsOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overrides', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('branch', models.OneToOneField(db_column='branch_id', on_delete=django.db.models.deletion.CASCADE, related_name='settings_override', to='api.branch')),
            ],
            options={
                'db_table': 'branch_settings_overrides',
            },
        ),
    ]
