# Generated by Django 5.2.15 on 2026-09-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_backfill_employee_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileBlob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_column='name', unique=True)),
                ('content', models.BinaryField(db_column='content')),
                ('content_type', models.TextField(blank=True, db_column='content_type', default='')),
                ('size', models.BigIntegerField(db_column='size', default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
            ],
            options={
                'db_table': 'file_blobs',
            },
        ),
    ]
