# Generated by Django 5.2.15 on 2026-09-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_fileblob'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='co_emp_enabled',
            field=models.BooleanField(db_column='co_emp_enabled', default=False),
        ),
    ]
