# Generated by Django 5.2.15 on 2026-09-04 07:49

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_employee_co_emp_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollsettings',
            name='basic_percent',
            field=models.DecimalField(db_column='basic_percent', decimal_places=2, default=50, help_text="% of salary treated as Basic for the Compensation page's CTC breakdown. Does not affect payroll generation.", max_digits=5),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='bonus_eligibility_ceiling',
            field=models.DecimalField(db_column='bonus_eligibility_ceiling', decimal_places=2, default=21000, help_text='Employees earning at or below this monthly wage are bonus-eligible.', max_digits=10),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='bonus_fy_start_month',
            field=models.IntegerField(db_column='bonus_fy_start_month', default=4, help_text='Financial year start month (1-12). Default 4 = April (Indian FY).'),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='bonus_percent',
            field=models.DecimalField(db_column='bonus_percent', decimal_places=2, default=Decimal('8.33'), help_text='Statutory bonus % applied to eligible wages (Act range: 8.33 min, 20 max).', max_digits=5),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='bonus_wage_ceiling',
            field=models.DecimalField(db_column='bonus_wage_ceiling', decimal_places=2, default=7000, help_text='Monthly wage ceiling used in the bonus calculation base -min(basic, this) per record.', max_digits=10),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='hra_percent',
            field=models.DecimalField(db_column='hra_percent', decimal_places=2, default=20, help_text="% of salary treated as HRA for the Compensation page's CTC breakdown. Does not affect payroll generation.", max_digits=5),
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.TextField(db_column='financial_year')),
                ('records_considered', models.IntegerField(db_column='records_considered')),
                ('calculation_base', models.DecimalField(db_column='calculation_base', decimal_places=2, help_text="Sum of min(basic, bonus_wage_ceiling) across the FY's salary slips.", max_digits=10)),
                ('bonus_percent_applied', models.DecimalField(db_column='bonus_percent_applied', decimal_places=2, max_digits=5)),
                ('bonus_amount', models.DecimalField(db_column='bonus_amount', decimal_places=2, max_digits=10)),
                ('status', models.TextField(choices=[('calculated', 'Calculated'), ('approved', 'Approved'), ('paid', 'Paid')], default='calculated')),
                ('notes', models.TextField(blank=True, null=True)),
                ('computed_by', models.TextField(blank=True, db_column='computed_by', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='api.employee')),
            ],
            options={
                'db_table': 'bonuses',
                'ordering': ['-created_at'],
                'unique_together': {('employee', 'financial_year')},
            },
        ),
    ]
