# Generated by Django 5.2.15 on 2026-09-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_payrollsettings_basic_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancedayrecord',
            name='late_afternoon',
            field=models.BooleanField(db_column='late_afternoon', default=False),
        ),
        migrations.AddField(
            model_name='attendancedayrecord',
            name='permission_afternoon',
            field=models.BooleanField(db_column='permission_afternoon', default=False),
        ),
        migrations.AddField(
            model_name='attendancedayrecord',
            name='permission_afternoon_with_request',
            field=models.BooleanField(db_column='permission_afternoon_with_request', default=False),
        ),
        migrations.AddField(
            model_name='attendancedayrecord',
            name='permission_departure',
            field=models.BooleanField(db_column='permission_departure', default=False),
        ),
        migrations.AddField(
            model_name='attendancedayrecord',
            name='permission_departure_with_request',
            field=models.BooleanField(db_column='permission_departure_with_request', default=False),
        ),
        migrations.AddField(
            model_name='attendancedayrecord',
            name='permission_escalated_to_half_shift',
            field=models.BooleanField(db_column='permission_escalated_to_half_shift', default=False),
        ),
        migrations.AddField(
            model_name='attendancedayrecord',
            name='permission_morning',
            field=models.BooleanField(db_column='permission_morning', default=False),
        ),
        migrations.AddField(
            model_name='attendancedayrecord',
            name='permission_morning_with_request',
            field=models.BooleanField(db_column='permission_morning_with_request', default=False),
        ),
        migrations.AddField(
            model_name='attendancedayrecord',
            name='permission_zone_count',
            field=models.IntegerField(db_column='permission_zone_count', default=0),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='afternoon_late_can_cause_half_shift',
            field=models.BooleanField(db_column='afternoon_late_can_cause_half_shift', default=True, help_text='Strict mode only. When on, a lunch return beyond the afternoon Late + Permission windows caps the day at Half Shift, the same way an arrival/departure edge already can. When off, a late lunch return is only ever flagged (never demotes shift value) -matches behavior before this feature existed.'),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='afternoon_late_window_minutes',
            field=models.IntegerField(db_column='afternoon_late_window_minutes', default=60, help_text='Strict mode only. Minutes past the lunch-return deadline (punch2 + lunch_duration_minutes) during which a late return is flagged Night Late but does not affect shift value. Beyond this, the afternoon Permission zone begins.'),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='afternoon_permission_window_minutes',
            field=models.IntegerField(db_column='afternoon_permission_window_minutes', default=60, help_text='Strict mode only. Extra minutes past afternoon_late_window_minutes during which a late lunch return is auto-detected as Permission. Beyond this window, see afternoon_late_can_cause_half_shift.'),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='max_permissions_per_day',
            field=models.IntegerField(db_column='max_permissions_per_day', default=1, help_text='Staff only. Maximum shift edges (morning arrival, lunch return, departure) per day that may resolve to Permission status. Any edge beyond this on the same day escalates to Half Shift.'),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='max_permissions_per_week',
            field=models.IntegerField(db_column='max_permissions_per_week', default=2, help_text='Staff only. Maximum Permission-zone edges per ISO week (Mon-Sun) across all days. Once exhausted, further edges that week escalate to Half Shift even if under the daily cap.'),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='permission_window_minutes',
            field=models.IntegerField(db_column='permission_window_minutes', default=60, help_text='Staff only. Extra minutes past shift_punctuality_window_minutes (on either the arrival or departure edge) during which a punch is auto-detected as Permission instead of Half Shift. Past this window too, the day is Half Shift.'),
        ),
        migrations.AlterField(
            model_name='payrollsettings',
            name='shift_punctuality_window_minutes',
            field=models.IntegerField(db_column='shift_punctuality_window_minutes', default=60, help_text="Staff only. Even with a first+last punch pair, Full Shift also requires the first punch within this many minutes of the employee's assigned shift start time, and the last punch within the same window of the assigned shift end time -otherwise the day moves into the Permission zone (see permission_window_minutes) or, past that, is capped at Half Shift. Employees with no assigned shift have no reference to check against, so this never applies to them."),
        ),
        migrations.AlterField(
            model_name='payrollsettings',
            name='without_permission_free_allowance',
            field=models.IntegerField(db_column='without_permission_free_allowance', default=0, help_text='Free Permission-zone-without-a-submitted-request occurrences allowed per employee per month before any shift deduction applies.'),
        ),
    ]
