# Generated by Django 5.2.15 on 2026-09-05 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_attendancedayrecord_late_afternoon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancedayrecord',
            name='is_compensation_day',
            field=models.BooleanField(db_column='is_compensation_day', default=False),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='ot_compensation_type',
            field=models.TextField(db_column='ot_compensation_type', default='pay', help_text="Company-wide default: 'pay' (one day's equivalent salary added to the next payroll run as OT) or 'relaxation' (a paid Alternative Day credit HR can redeem later). Snapshotted onto each OvertimeRecord at announce time; HR may override per-batch."),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='ot_detection_enabled',
            field=models.BooleanField(db_column='ot_detection_enabled', default=False, help_text='Staff only. Off by default -OT is never detected until HR enables this.'),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='ot_threshold_minutes',
            field=models.IntegerField(db_column='ot_threshold_minutes', default=60, help_text="Minutes worked past the assigned shift's end time before a day is OT-eligible."),
        ),
        migrations.CreateModel(
            name='CompensationDayAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('leave_until_time', models.TimeField(blank=True, db_column='leave_until_time', null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('announced_by', models.TextField(blank=True, db_column='announced_by', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('branch', models.ForeignKey(blank=True, db_column='branch_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compensation_days', to='api.branch')),
                ('department', models.ForeignKey(blank=True, db_column='department_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compensation_days', to='api.department')),
                ('employees', models.ManyToManyField(blank=True, related_name='compensation_day_announcements', to='api.employee')),
            ],
            options={
                'db_table': 'compensation_day_announcements',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='OvertimeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift_end_time', models.TimeField(blank=True, db_column='shift_end_time', null=True)),
                ('last_punch_out', models.TimeField(db_column='last_punch_out')),
                ('ot_minutes', models.IntegerField(db_column='ot_minutes')),
                ('status', models.TextField(choices=[('detected', 'Detected'), ('announced', 'Announced'), ('rejected', 'Rejected')], default='detected')),
                ('compensation_type', models.TextField(blank=True, choices=[('pay', 'Pay'), ('relaxation', 'Relaxation')], db_column='compensation_type', null=True)),
                ('announced_by', models.TextField(blank=True, db_column='announced_by', null=True)),
                ('announced_at', models.DateTimeField(blank=True, db_column='announced_at', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='overtime_records', to='api.employee')),
            ],
            options={
                'db_table': 'overtime_records',
                'ordering': ['-date'],
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='CompensationLeaveCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(choices=[('available', 'Available'), ('used', 'Used')], default='available')),
                ('used_date', models.DateField(blank=True, db_column='used_date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='compensation_credits', to='api.employee')),
                ('source_overtime_record', models.ForeignKey(blank=True, db_column='source_overtime_record_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credits', to='api.overtimerecord')),
            ],
            options={
                'db_table': 'compensation_leave_credits',
                'ordering': ['-created_at'],
            },
        ),
    ]
