# Generated by Django 5.2.15 on 2026-09-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_attendancedayrecord_is_compensation_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollsettings',
            name='compensation_feature_enabled',
            field=models.BooleanField(db_column='compensation_feature_enabled', default=True),
        ),
    ]
