# Generated by Django 5.2.15 on 2026-09-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0083_payrollsettings_compensation_feature_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancedayrecord',
            name='is_informed',
            field=models.BooleanField(blank=True, db_column='is_informed', default=None, null=True),
        ),
    ]
