# Generated by Django 5.2.15 on 2026-09-07 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0084_attendancedayrecord_is_informed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_column='name')),
                ('phone', models.TextField(db_column='phone', unique=True)),
                ('aadhaar_number', models.TextField(blank=True, db_column='aadhaar_number', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
            ],
            options={
                'db_table': 'visitors',
            },
        ),
        migrations.CreateModel(
            name='OutpassRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.TextField(db_column='employee_name')),
                ('employee_code', models.TextField(db_column='employee_code')),
                ('destination', models.TextField(db_column='destination')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_column='submitted_at')),
                ('branch', models.ForeignKey(blank=True, db_column='branch_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outpass_records', to='api.branch')),
                ('employee', models.ForeignKey(blank=True, db_column='employee_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outpass_records', to='api.employee')),
            ],
            options={
                'db_table': 'outpass_records',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitorVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('why_came', models.TextField(blank=True, db_column='why_came', null=True)),
                ('whom_to_meet', models.TextField(db_column='whom_to_meet')),
                ('purpose', models.TextField(db_column='purpose')),
                ('visited_at', models.DateTimeField(auto_now_add=True, db_column='visited_at')),
                ('branch', models.ForeignKey(blank=True, db_column='branch_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_visits', to='api.branch')),
                ('visitor', models.ForeignKey(db_column='visitor_id', on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='api.visitor')),
            ],
            options={
                'db_table': 'visitor_visits',
                'ordering': ['-visited_at'],
            },
        ),
        migrations.CreateModel(
            name='GateQRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.TextField(choices=[('outpass', 'Outpass'), ('visitor', 'Visitor')], db_column='kind')),
                ('token', models.TextField(db_column='token', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('branch', models.ForeignKey(db_column='branch_id', on_delete=django.db.models.deletion.CASCADE, related_name='gate_qr_codes', to='api.branch')),
            ],
            options={
                'db_table': 'gate_qr_codes',
                'constraints': [models.UniqueConstraint(fields=('branch', 'kind'), name='uniq_branch_qr_kind')],
            },
        ),
    ]
