# Generated by Django 5.2.15 on 2026-09-08 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_visitor_outpassrecord_visitorvisit_gateqrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='outpassrecord',
            name='source',
            field=models.TextField(db_column='source', default='qr'),
        ),
        migrations.CreateModel(
            name='OutpassRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.TextField(db_column='destination')),
                ('reason', models.TextField(db_column='reason')),
                ('status', models.TextField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_column='status', default='pending')),
                ('source', models.TextField(choices=[('manual', 'Manual'), ('on_duty', 'On-Duty')], db_column='source', default='manual')),
                ('approver_role', models.TextField(blank=True, db_column='approver_role', null=True)),
                ('approved_by', models.TextField(blank=True, db_column='approved_by', null=True)),
                ('review_comment', models.TextField(blank=True, db_column='review_comment', null=True)),
                ('approved_at', models.DateTimeField(blank=True, db_column='approved_at', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='outpass_requests', to='api.employee')),
                ('on_duty_session', models.ForeignKey(blank=True, db_column='on_duty_session_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outpass_requests', to='api.ondutysession')),
                ('outpass_record', models.ForeignKey(blank=True, db_column='outpass_record_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.outpassrecord')),
            ],
            options={
                'db_table': 'outpass_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
