# Generated by Django 5.2.15 on 2026-09-08 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_outpassrecord_source_outpassrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancedayrecord',
            name='is_half_day_leave',
            field=models.BooleanField(db_column='is_half_day_leave', default=False),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='half_day_slot',
            field=models.TextField(blank=True, choices=[('morning', 'Morning (First Half)'), ('afternoon', 'Afternoon (Second Half)')], db_column='half_day_slot', null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='is_half_day',
            field=models.BooleanField(db_column='is_half_day', default=False),
        ),
    ]
