# Generated by Django 5.2.15 on 2026-09-08 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_seed_default_leave_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='outpassrequest',
            name='exited_at',
            field=models.DateTimeField(blank=True, db_column='exited_at', null=True),
        ),
        migrations.CreateModel(
            name='GateDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_column='name')),
                ('username', models.TextField(db_column='username', unique=True)),
                ('password_hash', models.TextField(db_column='password_hash')),
                ('login_token', models.TextField(db_column='login_token', unique=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('created_by', models.TextField(blank=True, db_column='created_by', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('last_login_at', models.DateTimeField(blank=True, db_column='last_login_at', null=True)),
                ('branch', models.ForeignKey(db_column='branch_id', on_delete=django.db.models.deletion.CASCADE, related_name='gate_devices', to='api.branch')),
            ],
            options={
                'db_table': 'gate_devices',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='outpassrequest',
            name='exit_gate',
            field=models.ForeignKey(blank=True, db_column='exit_gate_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exited_requests', to='api.gatedevice'),
        ),
        migrations.CreateModel(
            name='OutpassGateScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField(choices=[('success', 'Success'), ('already_scanned', 'Already Scanned'), ('expired', 'Expired'), ('not_approved', 'Not Approved'), ('invalid_qr', 'Invalid QR')], db_column='result')),
                ('message', models.TextField(db_column='message')),
                ('scanned_at', models.DateTimeField(auto_now_add=True, db_column='scanned_at')),
                ('employee', models.ForeignKey(blank=True, db_column='employee_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.employee')),
                ('gate', models.ForeignKey(blank=True, db_column='gate_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to='api.gatedevice')),
                ('outpass_request', models.ForeignKey(blank=True, db_column='outpass_request_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gate_scans', to='api.outpassrequest')),
            ],
            options={
                'db_table': 'outpass_gate_scans',
                'ordering': ['-scanned_at'],
            },
        ),
    ]
