# Generated by Django 5.2.15 on 2026-09-16 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0089_outpassrequest_exited_at_gatedevice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outpassgatescan',
            name='scan_type',
            field=models.TextField(choices=[('exit', 'Exit'), ('entry', 'Entry')], db_column='scan_type', default='exit'),
        ),
        migrations.AddField(
            model_name='outpassrequest',
            name='entered_at',
            field=models.DateTimeField(blank=True, db_column='entered_at', null=True),
        ),
        migrations.AddField(
            model_name='outpassrequest',
            name='entry_gate',
            field=models.ForeignKey(blank=True, db_column='entry_gate_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_requests', to='api.gatedevice'),
        ),
        migrations.AddField(
            model_name='outpassrequest',
            name='return_qr_generated_at',
            field=models.DateTimeField(blank=True, db_column='return_qr_generated_at', null=True),
        ),
        migrations.AlterField(
            model_name='outpassgatescan',
            name='result',
            field=models.TextField(choices=[('success', 'Success'), ('already_scanned', 'Already Scanned'), ('expired', 'Expired'), ('not_approved', 'Not Approved'), ('invalid_qr', 'Invalid QR'), ('not_exited', 'Not Yet Exited')], db_column='result'),
        ),
    ]
