# Generated by Django 5.2.15 on 2026-09-16 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0090_outpassgatescan_scan_type_outpassrequest_entered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorvisit',
            name='meeting_employee',
            field=models.ForeignKey(blank=True, db_column='meeting_employee_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_visits_as_host', to='api.employee'),
        ),
        migrations.AddField(
            model_name='visitorvisit',
            name='notified_email_at',
            field=models.DateTimeField(blank=True, db_column='notified_email_at', null=True),
        ),
        migrations.AddField(
            model_name='visitorvisit',
            name='notified_whatsapp_at',
            field=models.DateTimeField(blank=True, db_column='notified_whatsapp_at', null=True),
        ),
        migrations.AlterField(
            model_name='whatsappmessagelog',
            name='document_type',
            field=models.TextField(choices=[('salary_slip', 'Salary Slip'), ('id_card', 'ID Card'), ('offer_letter', 'Offer Letter'), ('experience_letter', 'Experience Letter'), ('resignation_letter', 'Resignation Letter'), ('other', 'Other Document'), ('visitor_notification', 'Visitor Notification')], db_column='document_type'),
        ),
        migrations.CreateModel(
            name='ReceptionDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_column='name')),
                ('username', models.TextField(db_column='username', unique=True)),
                ('password_hash', models.TextField(db_column='password_hash')),
                ('login_token', models.TextField(db_column='login_token', unique=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('created_by', models.TextField(blank=True, db_column='created_by', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('last_login_at', models.DateTimeField(blank=True, db_column='last_login_at', null=True)),
                ('branch', models.ForeignKey(db_column='branch_id', on_delete=django.db.models.deletion.CASCADE, related_name='reception_devices', to='api.branch')),
            ],
            options={
                'db_table': 'reception_devices',
                'ordering': ['name'],
            },
        ),
    ]
