# Generated by Django 5.2.15 on 2026-09-17 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0091_visitorvisit_meeting_employee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeaBreakRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_minutes', models.IntegerField(db_column='allowed_minutes', default=15)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'tea_break_rule',
            },
        ),
        migrations.CreateModel(
            name='TeaBreakLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_at', models.DateTimeField(db_column='out_at')),
                ('in_at', models.DateTimeField(blank=True, db_column='in_at', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='tea_break_logs', to='api.employee')),
                ('in_gate', models.ForeignKey(blank=True, db_column='in_gate_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.gatedevice')),
                ('out_gate', models.ForeignKey(blank=True, db_column='out_gate_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.gatedevice')),
            ],
            options={
                'db_table': 'tea_break_logs',
                'ordering': ['-out_at'],
            },
        ),
    ]
