# Generated by Django 5.2.16 on 2026-09-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_teabreakrule_teabreaklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepermission',
            name='duration_minutes',
            field=models.IntegerField(blank=True, choices=[(30, '30 minutes'), (45, '45 minutes'), (60, '60 minutes'), (90, '90 minutes')], db_column='duration_minutes', null=True),
        ),
        migrations.AddField(
            model_name='employeepermission',
            name='type',
            field=models.TextField(blank=True, choices=[('Early Out', 'Early Out'), ('Late In', 'Late In'), ('Short Leave', 'Short Leave')], db_column='type', null=True),
        ),
        migrations.AddField(
            model_name='outpassrequest',
            name='expected_return_at',
            field=models.DateTimeField(blank=True, db_column='expected_return_at', null=True),
        ),
        migrations.AddField(
            model_name='outpassrequest',
            name='pass_type',
            field=models.TextField(blank=True, choices=[('official', 'Official / Mill Duty'), ('personal', 'Personal Emergency'), ('early_dismissal', 'Early Shift Dismissal')], db_column='pass_type', null=True),
        ),
    ]
