# Generated by Django 5.2.16 on 2026-09-21 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0093_employeepermission_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='nationality',
            field=models.TextField(blank=True, db_column='nationality', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='password_updated_at',
            field=models.DateTimeField(blank=True, db_column='password_updated_at', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='staff_tier',
            field=models.TextField(blank=True, db_column='staff_tier', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='workstation',
            field=models.TextField(blank=True, db_column='workstation', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='zone',
            field=models.TextField(blank=True, db_column='zone', null=True),
        ),
        migrations.CreateModel(
            name='FamilyDependent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('relation', models.TextField(choices=[('spouse', 'Spouse'), ('child', 'Child'), ('father', 'Father'), ('mother', 'Mother'), ('sibling', 'Sibling'), ('other', 'Other')])),
                ('date_of_birth', models.DateField(blank=True, db_column='date_of_birth', null=True)),
                ('is_insurance_nominee', models.BooleanField(db_column='is_insurance_nominee', default=False)),
                ('covered_under_health_scheme', models.BooleanField(db_column='covered_under_health_scheme', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='api.employee')),
            ],
            options={
                'db_table': 'family_dependents',
            },
        ),
    ]
