# Generated by Django 5.2.15 on 2026-09-23 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0094_employee_nationality_employee_password_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollsettings',
            name='night_shift_enabled',
        ),
        migrations.DeleteModel(
            name='NightShiftRelaxation',
        ),
        migrations.DeleteModel(
            name='NightShiftRule',
        ),
    ]
