# Generated by Django 5.2.15 on 2026-09-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0095_remove_payrollsettings_night_shift_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppMediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_column='token', max_length=64, unique=True)),
                ('content', models.BinaryField(db_column='content')),
                ('filename', models.TextField(db_column='filename')),
                ('mime_type', models.TextField(db_column='mime_type')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('expires_at', models.DateTimeField(db_column='expires_at')),
            ],
            options={
                'db_table': 'whatsapp_media_asset',
            },
        ),
        migrations.RemoveField(
            model_name='whatsappmessagelog',
            name='meta_message_id',
        ),
        migrations.RemoveField(
            model_name='whatsappmessagetemplate',
            name='meta_language_code',
        ),
        migrations.RemoveField(
            model_name='whatsappmessagetemplate',
            name='meta_template_name',
        ),
        migrations.AddField(
            model_name='whatsappmessagelog',
            name='gupshup_message_id',
            field=models.TextField(blank=True, db_column='gupshup_message_id', default=''),
        ),
        migrations.AddField(
            model_name='whatsappmessagetemplate',
            name='gupshup_template_id',
            field=models.TextField(blank=True, db_column='gupshup_template_id', default=''),
        ),
    ]
