# Generated by Django 5.2.15 on 2026-09-25 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0097_waclient_whatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.TextField(choices=[('login', 'Login'), ('reset', 'Password reset')], db_column='purpose')),
                ('code_hash', models.TextField(db_column='code_hash')),
                ('phone_number', models.TextField(db_column='phone_number')),
                ('attempts', models.IntegerField(db_column='attempts', default=0)),
                ('expires_at', models.DateTimeField(db_column='expires_at')),
                ('consumed_at', models.DateTimeField(blank=True, db_column='consumed_at', null=True)),
                ('requested_ip', models.TextField(blank=True, db_column='requested_ip', default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
            ],
            options={
                'db_table': 'employee_otp',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_login_enabled', models.BooleanField(db_column='otp_login_enabled', default=True)),
                ('otp_reset_enabled', models.BooleanField(db_column='otp_reset_enabled', default=True)),
                ('password_login_enabled', models.BooleanField(db_column='password_login_enabled', default=True)),
                ('otp_expiry_minutes', models.IntegerField(db_column='otp_expiry_minutes', default=5)),
                ('absent_alert_enabled', models.BooleanField(db_column='absent_alert_enabled', default=False)),
                ('late_alert_enabled', models.BooleanField(db_column='late_alert_enabled', default=False)),
                ('four_punch_alert_enabled', models.BooleanField(db_column='four_punch_alert_enabled', default=False)),
                ('missing_punch_alert_enabled', models.BooleanField(db_column='missing_punch_alert_enabled', default=False)),
                ('geo_approval_enabled', models.BooleanField(db_column='geo_approval_enabled', default=False)),
                ('absent_extra_minutes', models.IntegerField(db_column='absent_extra_minutes', default=0)),
                ('four_punch_wait_minutes', models.IntegerField(db_column='four_punch_wait_minutes', default=10)),
                ('missing_punch_after_minutes', models.IntegerField(db_column='missing_punch_after_minutes', default=30)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'whatsapp_settings',
            },
        ),
        migrations.AddField(
            model_name='whatsappmessagelog',
            name='dedupe_key',
            field=models.TextField(blank=True, db_column='dedupe_key', default=''),
        ),
        migrations.AddField(
            model_name='whatsappmessagelog',
            name='message_text',
            field=models.TextField(blank=True, db_column='message_text', default=''),
        ),
        migrations.AddField(
            model_name='whatsappmessagelog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updated_at'),
        ),
        migrations.AlterField(
            model_name='whatsappmessagelog',
            name='document_type',
            field=models.TextField(choices=[('salary_slip', 'Salary Slip'), ('id_card', 'ID Card'), ('offer_letter', 'Offer Letter'), ('experience_letter', 'Experience Letter'), ('resignation_letter', 'Resignation Letter'), ('other', 'Other Document'), ('visitor_notification', 'Visitor Notification'), ('otp_login', 'Login OTP'), ('otp_reset', 'Password Reset OTP'), ('absent_alert', 'Absent / No Punch Alert'), ('late_alert', 'Late Attendance Alert'), ('four_punch_alert', '4-Punch Alert'), ('missing_punch_alert', 'Missing Punch Alert'), ('geo_approval', 'Geo Attendance Approval'), ('geo_punch_approval', 'Geo Punch Approval')], db_column='document_type'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessagelog',
            index=models.Index(fields=['status', '-created_at'], name='whatsapp_me_status_e4ff2a_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessagelog',
            index=models.Index(fields=['document_type', '-created_at'], name='whatsapp_me_documen_365f5a_idx'),
        ),
        migrations.AddConstraint(
            model_name='whatsappmessagelog',
            constraint=models.UniqueConstraint(condition=models.Q(('dedupe_key', ''), _negated=True), fields=('dedupe_key',), name='whatsapp_log_unique_dedupe_key'),
        ),
        migrations.AddField(
            model_name='employeeotp',
            name='employee',
            field=models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='otps', to='api.employee'),
        ),
        migrations.AddIndex(
            model_name='employeeotp',
            index=models.Index(fields=['employee', 'purpose', '-created_at'], name='employee_ot_employe_0bf26c_idx'),
        ),
    ]
