# Generated by Django 5.2.15 on 2026-09-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0098_whatsapp_control_otp_alerts'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappsettings',
            name='otp_activate_enabled',
            field=models.BooleanField(db_column='otp_activate_enabled', default=True),
        ),
        migrations.AlterField(
            model_name='employeeotp',
            name='purpose',
            field=models.TextField(choices=[('login', 'Login'), ('reset', 'Password reset'), ('activate', 'Account activation')], db_column='purpose'),
        ),
        migrations.AlterField(
            model_name='whatsappmessagelog',
            name='document_type',
            field=models.TextField(choices=[('salary_slip', 'Salary Slip'), ('id_card', 'ID Card'), ('offer_letter', 'Offer Letter'), ('experience_letter', 'Experience Letter'), ('resignation_letter', 'Resignation Letter'), ('other', 'Other Document'), ('visitor_notification', 'Visitor Notification'), ('otp_login', 'Login OTP'), ('otp_reset', 'Password Reset OTP'), ('otp_activate', 'Account Activation OTP'), ('absent_alert', 'Absent / No Punch Alert'), ('late_alert', 'Late Attendance Alert'), ('four_punch_alert', '4-Punch Alert'), ('missing_punch_alert', 'Missing Punch Alert'), ('geo_approval', 'Geo Attendance Approval'), ('geo_punch_approval', 'Geo Punch Approval')], db_column='document_type'),
        ),
    ]
