# Generated by Django 5.2.15 on 2026-09-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0099_whatsapp_otp_activation'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessagelog',
            name='related_module',
            field=models.TextField(blank=True, db_column='related_module', default=''),
        ),
        migrations.AddField(
            model_name='whatsappsettings',
            name='approval_notifications_enabled',
            field=models.BooleanField(db_column='approval_notifications_enabled', default=True),
        ),
        migrations.AddField(
            model_name='whatsappsettings',
            name='attendance_alerts_enabled',
            field=models.BooleanField(db_column='attendance_alerts_enabled', default=True),
        ),
        migrations.AddField(
            model_name='whatsappsettings',
            name='disabled_approval_modules',
            field=models.JSONField(blank=True, db_column='disabled_approval_modules', default=list),
        ),
        migrations.AddField(
            model_name='whatsappsettings',
            name='document_notifications_enabled',
            field=models.BooleanField(db_column='document_notifications_enabled', default=True),
        ),
        migrations.AddField(
            model_name='whatsappsettings',
            name='outpass_notifications_enabled',
            field=models.BooleanField(db_column='outpass_notifications_enabled', default=True),
        ),
        migrations.AddField(
            model_name='whatsappsettings',
            name='visitor_notification_enabled',
            field=models.BooleanField(db_column='visitor_notification_enabled', default=True),
        ),
        migrations.AlterField(
            model_name='whatsappmessagelog',
            name='document_type',
            field=models.TextField(db_column='document_type'),
        ),
    ]
