# Generated by Django 5.2.15 on 2026-09-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0100_whatsapp_central_layer'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileAppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.TextField(db_column='platform', default='android')),
                ('version', models.TextField(db_column='version')),
                ('download_url', models.TextField(db_column='download_url')),
                ('release_notes', models.TextField(blank=True, db_column='release_notes', default='')),
                ('is_mandatory', models.BooleanField(db_column='is_mandatory', default=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('created_by', models.TextField(blank=True, db_column='created_by', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'mobile_app_versions',
                'constraints': [models.UniqueConstraint(fields=('platform', 'version'), name='uniq_mobile_app_version_per_platform')],
            },
        ),
    ]
