# Generated by Django 5.2.15 on 2026-09-30 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0103_late_permission_half_day_rewrite'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.TextField(db_column='email_type', unique=True)),
                ('subject', models.TextField(blank=True, db_column='subject', default='')),
                ('message_body', models.TextField(blank=True, db_column='message_body', default='')),
                ('is_enabled', models.BooleanField(db_column='is_enabled', default=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'email_message_template',
            },
        ),
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emails_enabled', models.BooleanField(db_column='emails_enabled', default=True)),
                ('document_emails_enabled', models.BooleanField(db_column='document_emails_enabled', default=True)),
                ('visitor_emails_enabled', models.BooleanField(db_column='visitor_emails_enabled', default=True)),
                ('recruitment_emails_enabled', models.BooleanField(db_column='recruitment_emails_enabled', default=True)),
                ('daily_send_limit', models.IntegerField(db_column='daily_send_limit', default=0)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'email_settings',
            },
        ),
        migrations.CreateModel(
            name='EmailMessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.TextField(blank=True, db_column='recipient_name', default='')),
                ('recipient_email', models.TextField(blank=True, db_column='recipient_email', default='')),
                ('email_type', models.TextField(db_column='email_type')),
                ('related_module', models.TextField(blank=True, db_column='related_module', default='')),
                ('ref_id', models.IntegerField(blank=True, db_column='ref_id', null=True)),
                ('subject', models.TextField(blank=True, db_column='subject', default='')),
                ('message_text', models.TextField(blank=True, db_column='message_text', default='')),
                ('attachment_name', models.TextField(blank=True, db_column='attachment_name', default='')),
                ('status', models.TextField(db_column='status', default='sent')),
                ('error_message', models.TextField(blank=True, db_column='error_message', default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('employee', models.ForeignKey(blank=True, db_column='employee_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_messages', to='api.employee')),
                ('sent_by', models.ForeignKey(blank=True, db_column='sent_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_sent', to='api.hruser')),
            ],
            options={
                'db_table': 'email_message_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee', 'email_type'], name='email_messa_employe_090fcc_idx'), models.Index(fields=['status', '-created_at'], name='email_messa_status_73229a_idx'), models.Index(fields=['email_type', '-created_at'], name='email_messa_email_t_b88368_idx')],
            },
        ),
    ]
