# Generated by Django 5.2.15 on 2026-09-30 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0104_email_control'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollsettings',
            name='contact_note',
            field=models.TextField(blank=True, db_column='contact_note', default=''),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='hr_contact_email',
            field=models.TextField(blank=True, db_column='hr_contact_email', default=''),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='hr_contact_hours',
            field=models.TextField(blank=True, db_column='hr_contact_hours', default=''),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='hr_contact_name',
            field=models.TextField(db_column='hr_contact_name', default='HR Department'),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='hr_contact_phone',
            field=models.TextField(blank=True, db_column='hr_contact_phone', default=''),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='hr_contact_whatsapp',
            field=models.TextField(blank=True, db_column='hr_contact_whatsapp', default=''),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='support_contact_email',
            field=models.TextField(blank=True, db_column='support_contact_email', default=''),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='support_contact_hours',
            field=models.TextField(blank=True, db_column='support_contact_hours', default=''),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='support_contact_name',
            field=models.TextField(db_column='support_contact_name', default='Software Support'),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='support_contact_phone',
            field=models.TextField(blank=True, db_column='support_contact_phone', default=''),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='support_contact_whatsapp',
            field=models.TextField(blank=True, db_column='support_contact_whatsapp', default=''),
        ),
    ]
