# Generated by Django 5.2.15 on 2026-09-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0105_hr_contact_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salary_basic',
            field=models.DecimalField(blank=True, db_column='salary_basic', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary_ca',
            field=models.DecimalField(blank=True, db_column='salary_ca', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary_da',
            field=models.DecimalField(blank=True, db_column='salary_da', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary_other_allowance',
            field=models.DecimalField(blank=True, db_column='salary_other_allowance', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary_petrol_allowance',
            field=models.DecimalField(blank=True, db_column='salary_petrol_allowance', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary_retention_allowance',
            field=models.DecimalField(blank=True, db_column='salary_retention_allowance', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary_rha',
            field=models.DecimalField(blank=True, db_column='salary_rha', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary_special_allowance',
            field=models.DecimalField(blank=True, db_column='salary_special_allowance', decimal_places=2, max_digits=10, null=True),
        ),
    ]
