# Generated by Django 5.2.15 on 2026-09-30 10:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0106_salary_split'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancedayrecord',
            name='arrival_zone',
            field=models.CharField(blank=True, db_column='arrival_zone', db_default='', default='', max_length=12),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='arrival_extra_minutes',
            field=models.IntegerField(db_column='arrival_extra_minutes', db_default=20, default=20, help_text='Staff only. Extra minutes after the permission window that still count as the first half.'),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='arrival_late_window_minutes',
            field=models.IntegerField(db_column='arrival_late_window_minutes', db_default=60, default=60, help_text='Staff only. Minutes after the grace period that an arrival is plain Late.'),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='arrival_permission_window_minutes',
            field=models.IntegerField(db_column='arrival_permission_window_minutes', db_default=60, default=60, help_text='Staff only. Minutes after the Late window that an approved Morning Late-In permission still excuses.'),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='arrival_quarter_deduction',
            field=models.DecimalField(db_column='arrival_quarter_deduction', db_default=Decimal('0.25'), decimal_places=2, default=Decimal('0.25'), help_text='Staff only. Shift deducted for an arrival after the Late window that no permission covers (0 = none).', max_digits=3),
        ),
    ]
