# Generated by Django 5.2.15 on 2026-09-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0107_arrival_timeline'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalWorkflowConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_column='key', max_length=40, unique=True)),
                ('enabled', models.BooleanField(db_column='enabled', db_default=True, default=True)),
                ('steps', models.JSONField(blank=True, db_column='steps', null=True)),
                ('updated_by', models.TextField(blank=True, db_column='updated_by', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'approval_workflow_configs',
            },
        ),
        migrations.AddField(
            model_name='attendanceoverriderequest',
            name='approval_trail',
            field=models.JSONField(blank=True, db_column='approval_trail', null=True),
        ),
        migrations.AddField(
            model_name='casualleaverequest',
            name='approval_trail',
            field=models.JSONField(blank=True, db_column='approval_trail', null=True),
        ),
        migrations.AddField(
            model_name='employeepermission',
            name='approval_trail',
            field=models.JSONField(blank=True, db_column='approval_trail', null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='approval_trail',
            field=models.JSONField(blank=True, db_column='approval_trail', null=True),
        ),
        migrations.AddField(
            model_name='missingpunchrequest',
            name='approval_trail',
            field=models.JSONField(blank=True, db_column='approval_trail', null=True),
        ),
        migrations.AddField(
            model_name='ondutysession',
            name='approval_trail',
            field=models.JSONField(blank=True, db_column='approval_trail', null=True),
        ),
        migrations.AddField(
            model_name='outpassrequest',
            name='approval_trail',
            field=models.JSONField(blank=True, db_column='approval_trail', null=True),
        ),
        migrations.AddField(
            model_name='resignationrequest',
            name='approval_trail',
            field=models.JSONField(blank=True, db_column='approval_trail', null=True),
        ),
    ]
