# Generated by Django 5.2.15 on 2026-10-01 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0108_approval_workflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerEmployeeExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='hod_exclusions', to='api.employee')),
                ('manager', models.ForeignKey(db_column='manager_id', on_delete=django.db.models.deletion.CASCADE, related_name='employee_exclusions', to='api.departmentmanager')),
            ],
            options={
                'db_table': 'manager_employee_exclusions',
                'unique_together': {('manager', 'employee')},
            },
        ),
    ]
