# Generated by Django 5.2.15 on 2026-10-05 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0110_salary_split_component_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='hruser',
            name='is_md',
            field=models.BooleanField(db_column='is_md', db_default=False, default=False),
        ),
        migrations.AddField(
            model_name='hruser',
            name='md_assigned_at',
            field=models.DateTimeField(blank=True, db_column='md_assigned_at', null=True),
        ),
        migrations.AddConstraint(
            model_name='hruser',
            constraint=models.UniqueConstraint(condition=models.Q(('is_md', True)), fields=('is_md',), name='uniq_single_md'),
        ),
    ]
