# Generated by Django 5.2.15 on 2026-10-05 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0111_hruser_is_md'),
    ]

    operations = [
        migrations.CreateModel(
            name='MdAssistantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(db_default=True, default=True)),
                ('model', models.TextField(db_default='gemini-3.5-flash-lite', default='gemini-3.5-flash-lite')),
                ('fallback_models', models.TextField(blank=True, db_column='fallback_models', db_default='gemini-3.1-flash-lite,gemini-3.8-flash', default='gemini-3.1-flash-lite,gemini-3.8-flash')),
                ('thinking_level', models.TextField(db_column='thinking_level', db_default='low', default='low')),
                ('privacy_mode', models.BooleanField(db_column='privacy_mode', db_default=True, default=True)),
                ('max_tool_rounds', models.IntegerField(db_column='max_tool_rounds', db_default=5, default=5)),
                ('requests_per_minute', models.IntegerField(db_column='requests_per_minute', db_default=8, default=8)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('updated_by', models.TextField(blank=True, db_column='updated_by', null=True)),
            ],
            options={
                'db_table': 'md_assistant_settings',
            },
        ),
        migrations.CreateModel(
            name='MdAssistantUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('model', models.TextField()),
                ('requests', models.IntegerField(db_default=0, default=0)),
                ('prompt_tokens', models.BigIntegerField(db_column='prompt_tokens', db_default=0, default=0)),
                ('output_tokens', models.BigIntegerField(db_column='output_tokens', db_default=0, default=0)),
                ('rate_limited', models.IntegerField(db_column='rate_limited', db_default=0, default=0)),
                ('daily_limit_hit', models.BooleanField(db_column='daily_limit_hit', db_default=False, default=False)),
            ],
            options={
                'db_table': 'md_assistant_usage',
                'constraints': [models.UniqueConstraint(fields=('day', 'model'), name='uniq_md_usage_day_model')],
            },
        ),
        migrations.CreateModel(
            name='MdConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='md_conversations', to='api.hruser')),
            ],
            options={
                'db_table': 'md_conversations',
            },
        ),
        migrations.CreateModel(
            name='MdMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.TextField()),
                ('status', models.TextField(db_default='done', default='done')),
                ('content', models.TextField(blank=True, default='')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('input_mode', models.TextField(db_column='input_mode', db_default='text', default='text')),
                ('language', models.TextField(blank=True, null=True)),
                ('page_context', models.JSONField(blank=True, db_column='page_context', null=True)),
                ('model_used', models.TextField(blank=True, db_column='model_used', null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('started_at', models.DateTimeField(blank=True, db_column='started_at', null=True)),
                ('finished_at', models.DateTimeField(blank=True, db_column='finished_at', null=True)),
                ('conversation', models.ForeignKey(db_column='conversation_id', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.mdconversation')),
            ],
            options={
                'db_table': 'md_messages',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='mdconversation',
            index=models.Index(fields=['user', '-updated_at'], name='md_conversa_user_id_74b675_idx'),
        ),
        migrations.AddIndex(
            model_name='mdmessage',
            index=models.Index(fields=['conversation', 'id'], name='md_messages_convers_f51614_idx'),
        ),
    ]
