# Generated by Django 5.2.15 on 2026-10-06 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0112_md_assistant'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricUnknownPusher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.TextField(db_column='serial_number', unique=True)),
                ('first_seen_at', models.DateTimeField(db_column='first_seen_at')),
                ('last_seen_at', models.DateTimeField(db_column='last_seen_at')),
                ('last_remote_ip', models.TextField(blank=True, db_column='last_remote_ip', default='')),
                ('contact_count', models.IntegerField(db_column='contact_count', default=0)),
                ('punch_count', models.IntegerField(db_column='punch_count', default=0)),
            ],
            options={
                'db_table': 'biometric_unknown_pushers',
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.AddField(
            model_name='biometricdevice',
            name='last_data_at',
            field=models.DateTimeField(blank=True, db_column='last_data_at', null=True),
        ),
        migrations.AddField(
            model_name='biometricdevice',
            name='last_error',
            field=models.TextField(blank=True, db_column='last_error', db_default='', default=''),
        ),
        migrations.AddField(
            model_name='biometricdevice',
            name='last_error_at',
            field=models.DateTimeField(blank=True, db_column='last_error_at', null=True),
        ),
        migrations.AddField(
            model_name='biometricdevice',
            name='last_heartbeat_at',
            field=models.DateTimeField(blank=True, db_column='last_heartbeat_at', null=True),
        ),
        migrations.AddField(
            model_name='biometricdevice',
            name='last_punch_date',
            field=models.DateField(blank=True, db_column='last_punch_date', null=True),
        ),
        migrations.AddField(
            model_name='biometricdevice',
            name='last_punch_time',
            field=models.TimeField(blank=True, db_column='last_punch_time', null=True),
        ),
        migrations.AddField(
            model_name='biometricdevice',
            name='last_reachable_at',
            field=models.DateTimeField(blank=True, db_column='last_reachable_at', null=True),
        ),
        migrations.AddField(
            model_name='biometricdevice',
            name='last_remote_ip',
            field=models.TextField(blank=True, db_column='last_remote_ip', db_default='', default=''),
        ),
        migrations.AddField(
            model_name='biometricdevice',
            name='last_sync_error',
            field=models.TextField(blank=True, db_column='last_sync_error', db_default='', default=''),
        ),
        migrations.AddField(
            model_name='biometricdevice',
            name='last_sync_error_at',
            field=models.DateTimeField(blank=True, db_column='last_sync_error_at', null=True),
        ),
        migrations.AddField(
            model_name='biometricdevice',
            name='reported_config',
            field=models.JSONField(blank=True, db_column='reported_config', null=True),
        ),
        migrations.AddField(
            model_name='biometricdevice',
            name='reported_config_at',
            field=models.DateTimeField(blank=True, db_column='reported_config_at', null=True),
        ),
        migrations.CreateModel(
            name='BiometricProbe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(db_column='checked_at')),
                ('status', models.TextField()),
                ('latency_ms', models.FloatField(blank=True, db_column='latency_ms', null=True)),
                ('icmp_ms', models.FloatField(blank=True, db_column='icmp_ms', null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('detail', models.JSONField(blank=True, null=True)),
                ('steps', models.JSONField(blank=True, null=True)),
                ('checked_from', models.TextField(blank=True, db_column='checked_from', default='')),
                ('device', models.ForeignKey(db_column='device_id', on_delete=django.db.models.deletion.CASCADE, related_name='probes', to='api.biometricdevice')),
            ],
            options={
                'db_table': 'biometric_device_probes',
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['device', '-checked_at'], name='biometric_d_device__ddc060_idx')],
            },
        ),
    ]
