# Generated by Django 5.2.15 on 2026-10-06 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0113_biometric_device_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricFetchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.TextField(default='update')),
                ('status', models.TextField(default='running')),
                ('started_by', models.TextField(blank=True, db_column='started_by', default='')),
                ('range_label', models.TextField(blank=True, db_column='range_label', default='')),
                ('date_from', models.DateField(blank=True, db_column='date_from', null=True)),
                ('date_to', models.DateField(blank=True, db_column='date_to', null=True)),
                ('device_ids', models.JSONField(db_column='device_ids', default=list)),
                ('results', models.JSONField(default=list)),
                ('summary', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('finished_at', models.DateTimeField(blank=True, db_column='finished_at', null=True)),
            ],
            options={
                'db_table': 'biometric_fetch_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='biometricdevice',
            name='capacity',
            field=models.JSONField(blank=True, db_column='capacity', null=True),
        ),
        migrations.AddField(
            model_name='biometricdevice',
            name='users_read_at',
            field=models.DateTimeField(blank=True, db_column='users_read_at', null=True),
        ),
        migrations.AddField(
            model_name='biometricdevice',
            name='users_read_error',
            field=models.TextField(blank=True, db_column='users_read_error', db_default='', default=''),
        ),
        migrations.CreateModel(
            name='BiometricDeviceUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(db_column='uid')),
                ('user_id', models.TextField(db_column='user_id', db_index=True)),
                ('name', models.TextField(blank=True, default='')),
                ('privilege', models.IntegerField(default=0)),
                ('card', models.BigIntegerField(default=0)),
                ('has_password', models.BooleanField(db_column='has_password', default=False)),
                ('group', models.TextField(blank=True, default='')),
                ('read_at', models.DateTimeField(db_column='read_at')),
                ('device', models.ForeignKey(db_column='device_id', on_delete=django.db.models.deletion.CASCADE, related_name='device_users', to='api.biometricdevice')),
            ],
            options={
                'db_table': 'biometric_device_users',
                'ordering': ['device_id', 'uid'],
                'indexes': [models.Index(fields=['device', 'user_id'], name='biometric_d_device__b5037f_idx')],
                'unique_together': {('device', 'uid')},
            },
        ),
    ]
