# Generated by Django 5.2.15 on 2026-10-09 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0114_biometric_device_control'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricDeviceOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.TextField()),
                ('status', models.TextField(default='running')),
                ('params', models.JSONField(blank=True, default=dict)),
                ('actor', models.JSONField(blank=True, default=dict)),
                ('results', models.JSONField(blank=True, default=dict)),
                ('final', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('finished_at', models.DateTimeField(blank=True, db_column='finished_at', null=True)),
            ],
            options={
                'db_table': 'biometric_device_operations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BiometricSiteConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('token_hash', models.CharField(blank=True, db_column='token_hash', db_index=True, default='', max_length=64)),
                ('pairing_hash', models.CharField(blank=True, db_column='pairing_hash', default='', max_length=64)),
                ('pairing_expires_at', models.DateTimeField(blank=True, db_column='pairing_expires_at', null=True)),
                ('paired_at', models.DateTimeField(blank=True, db_column='paired_at', null=True)),
                ('punch_sync_minutes', models.IntegerField(db_column='punch_sync_minutes', default=15)),
                ('punch_sync_days', models.IntegerField(db_column='punch_sync_days', default=2)),
                ('last_seen_at', models.DateTimeField(blank=True, db_column='last_seen_at', null=True)),
                ('last_remote_ip', models.TextField(blank=True, db_column='last_remote_ip', default='')),
                ('version', models.TextField(blank=True, default='')),
                ('hostname', models.TextField(blank=True, default='')),
                ('os_info', models.TextField(blank=True, db_column='os_info', default='')),
                ('status', models.JSONField(blank=True, default=dict)),
                ('created_by', models.TextField(blank=True, db_column='created_by', default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
            ],
            options={
                'db_table': 'biometric_site_connectors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BiometricConnectorJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.TextField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.TextField(default='queued')),
                ('result', models.JSONField(blank=True, null=True)),
                ('error_code', models.TextField(blank=True, db_column='error_code', default='')),
                ('error_message', models.TextField(blank=True, db_column='error_message', default='')),
                ('attempts', models.IntegerField(default=0)),
                ('last_seq', models.IntegerField(db_column='last_seq', default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('claimed_at', models.DateTimeField(blank=True, db_column='claimed_at', null=True)),
                ('finished_at', models.DateTimeField(blank=True, db_column='finished_at', null=True)),
                ('expires_at', models.DateTimeField(db_column='expires_at')),
                ('device', models.ForeignKey(db_column='device_id', on_delete=django.db.models.deletion.CASCADE, related_name='connector_jobs', to='api.biometricdevice')),
                ('operation', models.ForeignKey(blank=True, db_column='operation_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='api.biometricdeviceoperation')),
                ('connector', models.ForeignKey(db_column='connector_id', on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='api.biometricsiteconnector')),
            ],
            options={
                'db_table': 'biometric_connector_jobs',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='BiometricConnectorPunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField(db_column='user_id')),
                ('punch_date', models.DateField(db_column='punch_date')),
                ('punch_time', models.TimeField(db_column='punch_time')),
                ('status', models.SmallIntegerField(default=0)),
                ('job', models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, related_name='punches', to='api.biometricconnectorjob')),
            ],
            options={
                'db_table': 'biometric_connector_punches',
            },
        ),
        migrations.AddField(
            model_name='biometricdevice',
            name='connector',
            field=models.ForeignKey(blank=True, db_column='connector_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='api.biometricsiteconnector'),
        ),
        migrations.AddIndex(
            model_name='biometricconnectorjob',
            index=models.Index(fields=['connector', 'status'], name='biometric_c_connect_9f9396_idx'),
        ),
        migrations.AddIndex(
            model_name='biometricconnectorjob',
            index=models.Index(fields=['operation'], name='biometric_c_operati_e5e3fa_idx'),
        ),
    ]
