# Generated by Django 5.2.15 on 2026-10-09 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0115_biometric_site_connector'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='biometricconnectorjob',
            index=models.Index(fields=['status', 'expires_at'], name='biometric_c_status_0cecbe_idx'),
        ),
    ]
