import {
  ArrowRightLeft,
  BadgeCheck,
  Banknote,
  BarChart3,
  Briefcase,
  Building2,
  Cake,
  Calculator,
  CalendarCheck,
  CalendarClock,
  CalendarDays,
  CalendarOff,
  ClipboardList,
  Clock,
  Coffee,
  DoorOpen,
  FileSpreadsheet,
  FileText,
  Fingerprint,
  FolderOpen,
  Gift,
  GraduationCap,
  Handshake,
  HeartPulse,
  History,
  Hourglass,
  IdCard,
  KeyRound,
  Landmark,
  Layers,
  LogIn,
  LogOut,
  MapPin,
  Percent,
  PieChart,
  QrCode,
  Receipt,
  ScanLine,
  Scale,
  ShieldCheck,
  Sigma,
  Smartphone,
  Timer,
  TrendingUp,
  TriangleAlert,
  UserMinus,
  UserPlus,
  UserRound,
  Users,
  Wallet,
  Award,
  UserX,
  Phone,
  Network,
  Heart,
  HandCoins,
  Grid3x3,
  ArrowLeftRight,
  ClipboardCheck,
  CalendarRange,
  Inbox,
  type LucideIcon,
} from "lucide-react";

/** Icon names the backend may send (categories and reports) -> components. Explicit on purpose: importing
 *  the whole lucide namespace would defeat tree-shaking. Unknown names fall back to FileText. */
const ICONS: Record<string, LucideIcon> = {
  AlertTriangle: TriangleAlert, // the older lucide name some reports use
  ArrowRightLeft,
  BadgeCheck,
  Banknote,
  BarChart3,
  Briefcase,
  Building2,
  Cake,
  Calculator,
  CalendarCheck,
  CalendarClock,
  CalendarDays,
  CalendarOff,
  ClipboardList,
  Clock,
  Coffee,
  DoorOpen,
  FileSpreadsheet,
  FileText,
  Fingerprint,
  FolderOpen,
  Gift,
  GraduationCap,
  Handshake,
  HeartPulse,
  History,
  Hourglass,
  IdCard,
  KeyRound,
  Landmark,
  Layers,
  LogIn,
  LogOut,
  MapPin,
  Percent,
  PieChart,
  QrCode,
  Receipt,
  ScanLine,
  Scale,
  ShieldCheck,
  Sigma,
  Smartphone,
  Timer,
  TrendingUp,
  TriangleAlert,
  UserMinus,
  UserPlus,
  UserRound,
  Users,
  Wallet,
  Award,
  UserX,
  Phone,
  Network,
  Heart,
  HandCoins,
  Grid3x3,
  ArrowLeftRight,
  ClipboardCheck,
  CalendarRange,
  Inbox,
};

export function iconFor(name: string | null | undefined): LucideIcon {
  return (name && ICONS[name]) || FileText;
}

/** Accent colours per category: icon chip + soft background. */
export const CATEGORY_STYLE: Record<string, { chip: string; ring: string; text: string; dot: string }> = {
  payroll: {
    chip: "bg-emerald-50 text-emerald-700",
    ring: "ring-emerald-100",
    text: "text-emerald-700",
    dot: "bg-emerald-500",
  },
  attendance: { chip: "bg-sky-50 text-sky-700", ring: "ring-sky-100", text: "text-sky-700", dot: "bg-sky-500" },
  leave: {
    chip: "bg-violet-50 text-violet-700",
    ring: "ring-violet-100",
    text: "text-violet-700",
    dot: "bg-violet-500",
  },
  gate: { chip: "bg-amber-50 text-amber-700", ring: "ring-amber-100", text: "text-amber-700", dot: "bg-amber-500" },
  employees: {
    chip: "bg-indigo-50 text-indigo-700",
    ring: "ring-indigo-100",
    text: "text-indigo-700",
    dot: "bg-indigo-500",
  },
  finance: { chip: "bg-rose-50 text-rose-700", ring: "ring-rose-100", text: "text-rose-700", dot: "bg-rose-500" },
  admin: { chip: "bg-slate-100 text-slate-700", ring: "ring-slate-200", text: "text-slate-700", dot: "bg-slate-500" },
};

export function categoryStyle(id: string) {
  return CATEGORY_STYLE[id] ?? CATEGORY_STYLE.admin;
}
