// Fixtures for the Recruitment page's tests: the responses of every endpoint, shaped like the backend's and carrying
// the same numbers as the backend's test company (api/tests_md_recruitment.py), so a figure can be checked against it.

import type { MdEnvelope, Provenance } from "@/lib/md/types";
import type {
  FunnelStage,
  RecruitmentAttention,
  RecruitmentFunnel,
  RecruitmentJoiners,
  RecruitmentPositions,
  RecruitmentResignations,
  RecruitmentSources,
  RecruitmentSummary,
  RecruitmentTrend,
} from "./types";

export const PROVENANCE = (id: string, title: string): Provenance => ({
  id,
  title,
  dataset: "Test data",
  definition: `How ${title.toLowerCase()} is worked out.`,
  formula: null,
  rows: 3,
  filters: [],
  caveats: [],
});

const envelope = (provenance: string[] = [], notes: string[] = []): MdEnvelope => ({
  generatedAt: "2026-10-05T10:42:10",
  period: { start: "2026-07-08", end: "2026-10-05", preset: "last_90_days", label: "Last 90 days", days: 90 },
  scope: { branchIds: [], departmentIds: [], employmentType: null, description: "All units · all departments" },
  provenance: provenance.map((id) => PROVENANCE(id, id.replace(/-/g, " "))),
  notes,
});

const stage = (
  id: FunnelStage["id"],
  label: string,
  count: number | null,
  previousCount: number | null,
  previousLabel: string | null,
  note: string | null = null,
): FunnelStage => {
  const lost = count != null && previousCount != null ? previousCount - count : null;
  return {
    id,
    label,
    count,
    previousCount,
    previousLabel,
    ofPrevious: count != null && previousCount ? Math.round((count / previousCount) * 1000) / 10 : null,
    dropOff: lost,
    dropOffPct: lost != null && previousCount ? Math.round((lost / previousCount) * 1000) / 10 : null,
    note,
  };
};

const OFFER_NOTE =
  "Only the job board records a final selection, so this is job-board candidates only and is compared with the job-board candidates who were interviewed.";
const JOINED_NOTE =
  "Everyone who joined in the period, hired through any route. Applicants are not linked to the employee record they become, so this is not a share of those offered.";

export const FUNNEL_ALL: FunnelStage[] = [
  stage("applied", "Applied", 13, null, null),
  stage("screened", "Screened", 10, 13, "applied"),
  stage("shortlisted", "Shortlisted", 7, 10, "screened"),
  stage("interviewed", "Interviewed", 5, 7, "shortlisted"),
  stage("offered", "Offered", 1, 3, "interviewed (job board)", OFFER_NOTE),
  stage("joined", "Joined", 4, null, null, JOINED_NOTE),
];

const FUNNEL_BOARD: FunnelStage[] = [
  stage("applied", "Applied", 6, null, null),
  stage("screened", "Screened", 4, 6, "applied"),
  stage("shortlisted", "Shortlisted", 3, 4, "screened"),
  stage("interviewed", "Interviewed", 3, 3, "shortlisted"),
  stage("offered", "Offered", 1, 3, "interviewed"),
  stage("joined", "Joined", null, null, null),
];

const FUNNEL_SCREENING: FunnelStage[] = [
  stage("applied", "Applied", 7, null, null),
  stage("screened", "Screened", 6, 7, "applied"),
  stage("shortlisted", "Shortlisted", 4, 6, "screened"),
  stage("interviewed", "Interviewed", 2, 4, "shortlisted"),
  stage(
    "offered",
    "Offered",
    null,
    null,
    null,
    "Resume screening has no final selection: it ends at the interview invitation.",
  ),
  stage("joined", "Joined", null, null, null),
];

export const SUMMARY: RecruitmentSummary = {
  ...envelope([
    "open-positions",
    "vacancies",
    "position-age",
    "time-to-fill",
    "pipeline",
    "interviews",
    "joiners",
    "leavers",
    "attrition",
  ]),
  current: {
    openPositions: 4,
    vacancies: 5,
    departmentsWithGap: 2,
    stalePositions: 2,
    avgOpenDays: 49,
    oldestOpenDays: 82,
    avgTimeToFillDays: null,
    applicantsInPipeline: 11,
    pipelineJobBoard: 5,
    pipelineScreening: 6,
    interviewsNext7Days: 1,
    interviewsToday: 0,
    resignationsPending: 3,
    oldestPendingDays: 10,
    onNotice: 1,
    leaversNext30: 2,
    candidatesReceived: 13,
    candidatesSelected: 1,
    interviewsHeld: 2,
    joiners: 4,
    joinersStaff: 2,
    joinersProduction: 2,
    leavers: 4,
    leaversResigned: 2,
    leaversDeactivated: 2,
    earlyLeavers: 2,
    net: 0,
    resignationsRaised: 7,
    attritionPct: 8,
    attritionAnnualisedPct: 97.3,
    averageHeadcount: 50,
  },
  previous: {
    candidatesReceived: 2,
    candidatesSelected: 0,
    interviewsHeld: 0,
    joiners: 2,
    leavers: 1,
    net: 1,
    resignationsRaised: 0,
    attritionPct: 2,
  },
  changes: {
    candidatesReceived: { abs: 11, pct: 550 },
    candidatesSelected: { abs: 1, pct: null },
    interviewsHeld: { abs: 2, pct: null },
    joiners: { abs: 2, pct: 100 },
    leavers: { abs: 3, pct: 300 },
    net: { abs: -1, pct: -100 },
    resignationsRaised: { abs: 7, pct: null },
    attritionPct: { abs: 6, pct: 300 },
  },
  previousPeriod: { start: "2026-04-10", end: "2026-07-07", preset: null, label: "Previous 90 days", days: 90 },
  thresholds: { staleAfterDays: 45, pipelineActiveDays: 90, earlyAttritionDays: 90, resignationWarnAfterDays: 7 },
};

export const ATTENTION: RecruitmentAttention = {
  ...envelope(["attention-rules"]),
  items: [
    {
      id: "recruitment.stale-positions",
      severity: "warning",
      title: "2 open positions have been open for more than 45 days",
      detail: "Longest open: Accountant (Accounts), 82 days.",
      metric: "2 positions",
      page: "recruitment",
      ask: "Which positions have been open too long, and what is holding them up?",
    },
    {
      id: "recruitment.resignations-waiting",
      severity: "warning",
      title: "3 resignations waiting for a decision",
      detail: "The longest has waited 10 days. Waiting for: Department head (2), HR (1).",
      metric: "3 pending",
      page: "recruitment",
      ask: "Which resignations are waiting for a decision, and who needs to act?",
    },
    {
      id: "recruitment.hiring-ahead",
      severity: "good",
      title: "Hiring is ahead of exits: 7 joined and 6 left (last 90 days)",
      detail: "A net gain of 1 person.",
      metric: "+1 net",
      page: "recruitment",
      ask: "How is hiring doing compared with attrition?",
    },
  ],
};

export const FUNNEL: RecruitmentFunnel = {
  ...envelope(["funnel", "joiners"]),
  stages: FUNNEL_ALL,
  views: { jobBoard: FUNNEL_BOARD, screening: FUNNEL_SCREENING },
  byDepartment: [
    {
      departmentId: 10,
      department: "Stitching (Unit 1)",
      applied: 9,
      screened: 7,
      shortlisted: 5,
      interviewed: 4,
      offered: 1,
      joined: 3,
    },
    {
      departmentId: 11,
      department: "Cutting",
      applied: 4,
      screened: 3,
      shortlisted: 2,
      interviewed: 1,
      offered: 0,
      joined: 0,
    },
  ],
  departmentsShown: 2,
  departmentsTotal: 2,
  joiners: { total: 4, staff: 2, production: 2, linked: false },
};

export const SOURCES: RecruitmentSources = {
  ...envelope(["sources"]),
  channels: [
    {
      id: "job_board",
      label: "Job board applications",
      candidates: 6,
      progressed: 3,
      progressedPct: 50,
      progressedLabel: "called to interview",
      detail: null,
    },
    {
      id: "resume_upload",
      label: "Resumes uploaded by HR",
      candidates: 7,
      progressed: 4,
      progressedPct: 57.1,
      progressedLabel: "shortlisted or later",
      detail: "3 single · 4 bulk uploads",
    },
  ],
  total: 13,
  channelsRecorded: 2,
};

export const POSITIONS: RecruitmentPositions = {
  ...envelope(["open-positions", "position-age", "time-to-fill", "vacancies"]),
  summary: {
    open: 4,
    stale: 2,
    avgOpenDays: 49,
    oldestOpenDays: 82,
    withApplicants: 2,
    staleAfterDays: 45,
    avgTimeToFillDays: null,
  },
  positions: [
    {
      id: 3,
      title: "Accountant",
      departmentId: 12,
      department: "Accounts",
      unit: "Unit 1",
      postedOn: "2026-07-15",
      daysOpen: 82,
      stale: true,
      applicants: 0,
      stageMix: { applied: 0, attended: 0, selected: 0, rejected: 0, other: 0 },
      salaryRange: null,
    },
    {
      id: 1,
      title: "Sewing Supervisor",
      departmentId: 10,
      department: "Stitching (Unit 1)",
      unit: "Unit 1",
      postedOn: "2026-08-01",
      daysOpen: 65,
      stale: true,
      applicants: 6,
      stageMix: { applied: 2, attended: 1, selected: 1, rejected: 1, other: 1 },
      salaryRange: "₹22,000 - ₹26,000",
    },
    {
      id: 5,
      title: "Driver",
      departmentId: null,
      department: null,
      unit: null,
      postedOn: "2026-09-01",
      daysOpen: 34,
      stale: false,
      applicants: 0,
      stageMix: { applied: 0, attended: 0, selected: 0, rejected: 0, other: 0 },
      salaryRange: null,
    },
    {
      id: 2,
      title: "Cutting Master",
      departmentId: 11,
      department: "Cutting",
      unit: "Unit 1",
      postedOn: "2026-09-20",
      daysOpen: 15,
      stale: false,
      applicants: 2,
      stageMix: { applied: 1, attended: 1, selected: 0, rejected: 0, other: 0 },
      salaryRange: null,
    },
  ],
  positionsShown: 4,
  headcountGap: {
    applicable: true,
    required: 50,
    current: 48,
    vacancies: 5,
    surplus: 3,
    departmentsWithGap: 2,
    departmentsTotal: 4,
    departments: [
      {
        departmentId: 10,
        department: "Stitching (Unit 1)",
        unit: "Unit 1",
        required: 6,
        current: 2,
        vacancy: 4,
        surplus: 0,
        fillPct: 33.3,
        openJobs: 1,
        shortlisted: 0,
      },
      {
        departmentId: 11,
        department: "Cutting",
        unit: "Unit 1",
        required: 3,
        current: 2,
        vacancy: 1,
        surplus: 0,
        fillPct: 66.7,
        openJobs: 1,
        shortlisted: 1,
      },
      {
        departmentId: 13,
        department: "Stitching (Unit 2)",
        unit: "Unit 2",
        required: 1,
        current: 1,
        vacancy: 0,
        surplus: 0,
        fillPct: 100,
        openJobs: 0,
        shortlisted: 0,
      },
      {
        departmentId: 12,
        department: "Accounts",
        unit: "Unit 1",
        required: 40,
        current: 43,
        vacancy: 0,
        surplus: 3,
        fillPct: 107.5,
        openJobs: 1,
        shortlisted: 0,
      },
    ],
  },
};

export const RESIGNATIONS: RecruitmentResignations = {
  ...envelope(["resignations-pending", "notice", "outlook", "resignations-raised", "reasons"]),
  summary: {
    pending: 3,
    oldestPendingDays: 10,
    waitingOn: [
      { label: "Department head", count: 2 },
      { label: "HR", count: 1 },
    ],
    onNotice: 1,
    raised: 7,
    approved: 4,
    rejected: 1,
    stillPending: 2,
    avgDaysToDecision: 5.5,
    warnAfterDays: 7,
  },
  pending: [
    {
      id: 11,
      employeeId: 1,
      employeeName: "Anil Test",
      department: "Stitching (Unit 1)",
      departmentId: 10,
      designation: "Sewing Supervisor",
      requestedOn: "2026-09-25",
      daysWaiting: 10,
      lastWorkingDate: "2026-10-25",
      noticeDays: 30,
      daysToLastDay: 20,
      status: "pending",
      waitingFor: ["hod"],
      waitingForText: "Department head",
    },
    {
      id: 12,
      employeeId: 6,
      employeeName: "Anita Test",
      department: "Stitching (Unit 2)",
      departmentId: 13,
      designation: null,
      requestedOn: "2026-09-30",
      daysWaiting: 5,
      lastWorkingDate: "2026-11-20",
      noticeDays: 51,
      daysToLastDay: 46,
      status: "dept_approved",
      waitingFor: ["hr"],
      waitingForText: "HR",
    },
    {
      id: 13,
      employeeId: 7,
      employeeName: "Ajay Test",
      department: "Accounts",
      departmentId: 12,
      designation: null,
      requestedOn: "2026-10-02",
      daysWaiting: 3,
      lastWorkingDate: null,
      noticeDays: null,
      daysToLastDay: null,
      status: "pending",
      waitingFor: ["hod"],
      waitingForText: "Department head",
    },
  ],
  pendingShown: 3,
  onNotice: [
    {
      id: 14,
      employeeId: 15,
      employeeName: "Leena Test",
      department: "Cutting",
      departmentId: 11,
      designation: null,
      approvedOn: "2026-10-01",
      lastWorkingDate: "2026-10-20",
      daysLeft: 15,
    },
  ],
  onNoticeShown: 1,
  reasons: [
    { id: "family", label: "Family or personal", count: 2, pct: 28.6 },
    { id: "pay", label: "Pay or a better job offer", count: 2, pct: 28.6 },
    { id: "health", label: "Health or medical", count: 1, pct: 14.3 },
    { id: "not_stated", label: "Not stated", count: 1, pct: 14.3 },
    { id: "relocation", label: "Relocation or distance", count: 1, pct: 14.3 },
  ],
  byDepartment: [
    { department: "Stitching (Unit 1)", departmentId: 10, raised: 3, pending: 1, approved: 1, rejected: 1 },
    { department: "Cutting", departmentId: 11, raised: 2, pending: 0, approved: 2, rejected: 0 },
    { department: "Stitching (Unit 2)", departmentId: 13, raised: 2, pending: 1, approved: 1, rejected: 0 },
  ],
  outlook: {
    next30: { days: 30, approved: 1, pending: 1, total: 2 },
    next60: { days: 60, approved: 1, pending: 2, total: 3 },
    withoutDate: 1,
    byDepartment: [
      { department: "Cutting", departmentId: 11, count: 1 },
      { department: "Stitching (Unit 1)", departmentId: 10, count: 1 },
      { department: "Stitching (Unit 2)", departmentId: 13, count: 1 },
    ],
  },
};

export const JOINERS: RecruitmentJoiners = {
  ...envelope(["joiners", "onboarding-docs", "early-attrition", "leavers"]),
  summary: {
    joiners: 4,
    staff: 2,
    production: 2,
    stillActive: 3,
    leftSinceJoining: 1,
    docsPending: 2,
    withoutJoinDate: 2,
  },
  list: [
    {
      employeeId: 3,
      employeeName: "Arun Test",
      department: "Stitching (Unit 1)",
      designation: null,
      unit: "Unit 1",
      type: "production",
      joinDate: "2026-09-30",
      active: true,
      docsMissing: 6,
    },
    {
      employeeId: 6,
      employeeName: "Anita Test",
      department: "Stitching (Unit 2)",
      designation: "Operator",
      unit: "Unit 2",
      type: "staff",
      joinDate: "2026-09-15",
      active: true,
      docsMissing: 0,
    },
    {
      employeeId: 22,
      employeeName: "Jeeva Test",
      department: "Stitching (Unit 1)",
      designation: null,
      unit: "Unit 1",
      type: "production",
      joinDate: "2026-09-03",
      active: false,
      docsMissing: null,
    },
    {
      employeeId: 2,
      employeeName: "Asha Test",
      department: "Stitching (Unit 1)",
      designation: null,
      unit: "Unit 1",
      type: "staff",
      joinDate: "2026-09-01",
      active: true,
      docsMissing: 3,
    },
  ],
  listShown: 4,
  byDepartment: [
    { department: "Stitching (Unit 1)", joiners: 3 },
    { department: "Stitching (Unit 2)", joiners: 1 },
  ],
  byUnit: [
    { unit: "Unit 1", joiners: 3 },
    { unit: "Unit 2", joiners: 1 },
  ],
  earlyAttrition: {
    windowDays: 90,
    leavers: 2,
    totalLeavers: 4,
    pct: 50,
    list: [
      {
        employeeId: 22,
        employeeName: "Jeeva Test",
        department: "Stitching (Unit 1)",
        joinDate: "2026-09-03",
        exitDate: "2026-09-25",
        daysServed: 22,
        approximate: true,
      },
      {
        employeeId: 12,
        employeeName: "Lokesh Test",
        department: "Stitching (Unit 1)",
        joinDate: "2026-08-10",
        exitDate: "2026-09-20",
        daysServed: 41,
        approximate: true,
      },
    ],
    listShown: 2,
    byDepartment: [{ department: "Stitching (Unit 1)", leavers: 2 }],
  },
};

const MONTHS: [string, string, number, number, number, number | null][] = [
  ["2025-11", "Nov 2025", 0, 0, 50, null],
  ["2025-12", "Dec 2025", 0, 0, 50, null],
  ["2026-01", "Jan 2026", 0, 0, 50, null],
  ["2026-02", "Feb 2026", 0, 0, 50, null],
  ["2026-03", "Mar 2026", 0, 0, 50, null],
  ["2026-04", "Apr 2026", 0, 0, 50, null],
  ["2026-05", "May 2026", 0, 0, 50, null],
  ["2026-06", "Jun 2026", 1, 0, 51, 4],
  ["2026-07", "Jul 2026", 0, 0, 51, 4],
  ["2026-08", "Aug 2026", 2, 1, 50, 4],
  ["2026-09", "Sep 2026", 4, 4, 50, 5],
  ["2026-10", "Oct 2026", 1, 1, 49, 5],
];

export const TREND: RecruitmentTrend = {
  ...envelope(["joiners", "leavers", "headcount-gap"]),
  months: MONTHS.map(([month, label, joiners, leavers, headcount, vacancies]) => ({
    month,
    label,
    partial: month === "2026-10",
    joiners,
    leavers,
    net: joiners - leavers,
    headcount,
    staffHeadcount: headcount - 2,
    vacancies,
  })),
  required: 50,
  totals: { joiners: 8, leavers: 6, net: 2 },
};

// ─── the same endpoints with nothing in them ───

const EMPTY_STAGES: FunnelStage[] = (
  ["applied", "screened", "shortlisted", "interviewed", "offered", "joined"] as const
).map((id) =>
  stage(
    id,
    id[0].toUpperCase() + id.slice(1),
    0,
    id === "applied" || id === "joined" ? null : 0,
    id === "applied" || id === "joined" ? null : "previous",
  ),
);

export const EMPTY = {
  summary: {
    ...SUMMARY,
    notes: [
      "No required headcount has been set (Recruitment, Required Roles), so vacancies against the plan cannot be shown.",
    ],
    current: {
      ...SUMMARY.current,
      openPositions: 0,
      vacancies: null,
      departmentsWithGap: null,
      stalePositions: 0,
      avgOpenDays: null,
      oldestOpenDays: null,
      applicantsInPipeline: 0,
      pipelineJobBoard: 0,
      pipelineScreening: 0,
      interviewsNext7Days: 0,
      resignationsPending: 0,
      oldestPendingDays: null,
      onNotice: 0,
      leaversNext30: 0,
      candidatesReceived: 0,
      candidatesSelected: 0,
      interviewsHeld: 0,
      joiners: 0,
      joinersStaff: 0,
      joinersProduction: 0,
      leavers: 0,
      leaversResigned: 0,
      leaversDeactivated: 0,
      earlyLeavers: 0,
      net: 0,
      resignationsRaised: 0,
      attritionPct: null,
      attritionAnnualisedPct: null,
      averageHeadcount: null,
    },
    changes: {
      candidatesReceived: { abs: 0, pct: null },
      candidatesSelected: { abs: 0, pct: null },
      interviewsHeld: { abs: 0, pct: null },
      joiners: { abs: 0, pct: null },
      leavers: { abs: 0, pct: null },
      net: { abs: 0, pct: null },
      resignationsRaised: { abs: 0, pct: null },
      attritionPct: null,
    },
  } satisfies RecruitmentSummary,
  attention: { ...ATTENTION, items: [] } satisfies RecruitmentAttention,
  funnel: {
    ...FUNNEL,
    stages: EMPTY_STAGES,
    views: { jobBoard: EMPTY_STAGES, screening: EMPTY_STAGES },
    byDepartment: [],
    departmentsShown: 0,
    departmentsTotal: 0,
    joiners: { total: 0, staff: 0, production: 0, linked: false },
  } satisfies RecruitmentFunnel,
  sources: {
    ...SOURCES,
    channels: SOURCES.channels.map((c) => ({ ...c, candidates: 0, progressed: 0, progressedPct: null })),
    total: 0,
  } satisfies RecruitmentSources,
  positions: {
    ...POSITIONS,
    summary: { ...POSITIONS.summary, open: 0, stale: 0, avgOpenDays: null, oldestOpenDays: null, withApplicants: 0 },
    positions: [],
    positionsShown: 0,
    headcountGap: {
      ...POSITIONS.headcountGap,
      required: null,
      current: null,
      vacancies: null,
      surplus: null,
      departmentsWithGap: null,
      departments: [],
      departmentsTotal: 0,
    },
  } satisfies RecruitmentPositions,
  resignations: {
    ...RESIGNATIONS,
    summary: {
      ...RESIGNATIONS.summary,
      pending: 0,
      oldestPendingDays: null,
      waitingOn: [],
      onNotice: 0,
      raised: 0,
      approved: 0,
      rejected: 0,
      stillPending: 0,
      avgDaysToDecision: null,
    },
    pending: [],
    pendingShown: 0,
    onNotice: [],
    onNoticeShown: 0,
    reasons: [],
    byDepartment: [],
    outlook: {
      next30: { days: 30, approved: 0, pending: 0, total: 0 },
      next60: { days: 60, approved: 0, pending: 0, total: 0 },
      withoutDate: 0,
      byDepartment: [],
    },
  } satisfies RecruitmentResignations,
  joiners: {
    ...JOINERS,
    summary: {
      joiners: 0,
      staff: 0,
      production: 0,
      stillActive: 0,
      leftSinceJoining: 0,
      docsPending: 0,
      withoutJoinDate: 0,
    },
    list: [],
    listShown: 0,
    byDepartment: [],
    byUnit: [],
    earlyAttrition: {
      windowDays: 90,
      leavers: 0,
      totalLeavers: 0,
      pct: null,
      list: [],
      listShown: 0,
      byDepartment: [],
    },
  } satisfies RecruitmentJoiners,
  trend: {
    ...TREND,
    months: TREND.months.map((m) => ({ ...m, joiners: 0, leavers: 0, net: 0, vacancies: null, partial: m.partial })),
    required: null,
    totals: { joiners: 0, leavers: 0, net: 0 },
  } satisfies RecruitmentTrend,
};

/** Every endpoint the page calls, answered from the fixtures above (for renderMdPage). */
export const FIXTURES = {
  "/api/md/recruitment/summary": SUMMARY,
  "/api/md/recruitment/attention": ATTENTION,
  "/api/md/recruitment/funnel": FUNNEL,
  "/api/md/recruitment/sources": SOURCES,
  "/api/md/recruitment/positions": POSITIONS,
  "/api/md/recruitment/resignations": RESIGNATIONS,
  "/api/md/recruitment/joiners": JOINERS,
  "/api/md/recruitment/trend": TREND,
};

export const EMPTY_FIXTURES = {
  "/api/md/recruitment/summary": EMPTY.summary,
  "/api/md/recruitment/attention": EMPTY.attention,
  "/api/md/recruitment/funnel": EMPTY.funnel,
  "/api/md/recruitment/sources": EMPTY.sources,
  "/api/md/recruitment/positions": EMPTY.positions,
  "/api/md/recruitment/resignations": EMPTY.resignations,
  "/api/md/recruitment/joiners": EMPTY.joiners,
  "/api/md/recruitment/trend": EMPTY.trend,
};
